# HSK 1-3 Chinese Characters (600 characters)
# Organized into themed weekly groups for daily SMS lessons
# 3 characters/day x 6 days/week = 18 new chars/week
# Full cycle: ~33 weeks to cover all characters

def _c(ch, py, t, mn, ecn, epy, een, gr, wk):
    return {"char": ch, "pinyin": py, "tone": t, "meaning": mn,
            "example_cn": ecn, "example_pinyin": epy, "example_en": een,
            "group": gr, "week": wk}

CHARACTERS = [

    # -- Week 1: Core Grammar --
    _c("的", "de", 5, "possessive particle ('s); descriptive marker", "这是我的书", "zhè shì wǒ de shū", "This is my book", "Core Grammar", 1),
    _c("是", "shì", 4, "to be (am/is/are)", "我是学生", "wǒ shì xuésheng", "I am a student", "Core Grammar", 1),
    _c("不", "bù", 4, "not; no (general negation)", "我不累", "wǒ bù lèi", "I am not tired", "Core Grammar", 1),
    _c("了", "le", 5, "completed action; change of state", "他来了", "tā lái le", "He came / He's here", "Core Grammar", 1),
    _c("在", "zài", 4, "at; in; on; to be at a place", "她在家", "tā zài jiā", "She is at home", "Core Grammar", 1),
    _c("有", "yǒu", 3, "to have; there is/are", "我有朋友", "wǒ yǒu péngyou", "I have friends", "Core Grammar", 1),
    _c("我", "wǒ", 3, "I; me", "我叫小明", "wǒ jiào Xiǎo Míng", "My name is Xiao Ming", "Pronouns", 1),
    _c("你", "nǐ", 3, "you (singular)", "你好吗", "nǐ hǎo ma", "How are you?", "Pronouns", 1),
    _c("他", "tā", 1, "he; him", "他是老师", "tā shì lǎoshī", "He is a teacher", "Pronouns", 1),
    _c("她", "tā", 1, "she; her", "她很漂亮", "tā hěn piàoliang", "She is very pretty", "Pronouns", 1),
    _c("它", "tā", 1, "it (animals/things)", "它是猫", "tā shì māo", "It is a cat", "Pronouns", 1),
    _c("们", "men", 5, "plural suffix: 我们=we, 他们=they", "我们是朋友", "wǒmen shì péngyou", "We are friends", "Pronouns", 1),

    # -- Week 2: Connectors --
    _c("这", "zhè", 4, "this; these", "这是什么", "zhè shì shénme", "What is this?", "Connectors", 2),
    _c("那", "nà", 4, "that; those; then", "那个人是谁", "nà gè rén shì shuí", "Who is that person?", "Connectors", 2),
    _c("和", "hé", 2, "and; with", "我和你都是学生", "wǒ hé nǐ dōu shì xuésheng", "You and I are both students", "Connectors", 2),
    _c("也", "yě", 3, "also; too", "我也喜欢", "wǒ yě xǐhuān", "I also like it", "Connectors", 2),
    _c("都", "dōu", 1, "all; both; already", "我们都去", "wǒmen dōu qù", "We all go", "Connectors", 2),
    _c("很", "hěn", 3, "very; quite", "她很高兴", "tā hěn gāoxìng", "She is very happy", "Connectors", 2),
    _c("没", "méi", 2, "not; haven't; without", "没有问题", "méiyǒu wèntí", "No problem", "Modal Verbs", 2),
    _c("就", "jiù", 4, "then; right away; only", "我就来", "wǒ jiù lái", "I'll be right there", "Modal Verbs", 2),
    _c("会", "huì", 4, "can; will; know how to", "你会游泳吗", "nǐ huì yóuyǒng ma", "Can you swim?", "Modal Verbs", 2),
    _c("能", "néng", 2, "can; able to; capable", "你能帮我吗", "nǐ néng bāng wǒ ma", "Can you help me?", "Modal Verbs", 2),
    _c("要", "yào", 4, "to want; need; will; must", "我要喝水", "wǒ yào hē shuǐ", "I want water", "Modal Verbs", 2),
    _c("可", "kě", 3, "can; may; approve", "你可以走了", "nǐ kěyǐ zǒu le", "You may go now", "Modal Verbs", 2),

    # -- Week 3: Particles --
    _c("吗", "ma", 5, "yes/no question particle", "你好吗", "nǐ hǎo ma", "How are you?", "Particles", 3),
    _c("呢", "ne", 5, "question particle (and you?; what about?)", "我很好，你呢", "wǒ hěn hǎo, nǐ ne", "I'm fine, and you?", "Particles", 3),
    _c("什", "shén", 2, "what (part of 什么)", "你叫什么名字", "nǐ jiào shénme míngzì", "What is your name?", "Question Words", 3),
    _c("么", "me", 5, "suffix (什么=what, 怎么=how)", "怎么了", "zěnme le", "What happened?", "Question Words", 3),
    _c("吧", "ba", 5, "suggestion particle (let's...)", "我们一起走吧", "wǒmen yīqǐ zǒu ba", "Let's go together", "Particles", 3),
    _c("啊", "a", 5, "exclamation; emphasis particle", "这里真美啊", "zhèlǐ zhēn měi a", "This place is really beautiful!", "Particles", 3),
    _c("再", "zài", 4, "again; once more; then", "我们明天再见", "wǒmen míngtiān zàijiàn", "We'll see each other again tomorrow", "Adverbs", 3),
    _c("还", "hái", 2, "still; yet; also; even more", "还有吗", "hái yǒu ma", "Is there still more?", "Adverbs", 3),
    _c("已", "yǐ", 3, "already (part of 已经)", "他已经到了", "tā yǐjīng dào le", "He has already arrived", "Adverbs", 3),
    _c("经", "jīng", 1, "to pass through; already (已经)", "我经过了那家店", "wǒ jīngguò le nà jiā diàn", "I passed by that shop", "Adverbs", 3),
    _c("才", "cái", 2, "only then; just now; only", "他才来", "tā cái lái", "He only just arrived", "Adverbs", 3),
    _c("又", "yòu", 4, "again; also; both...and...", "这个房间又大又亮", "zhè gè fángjiān yòu dà yòu liàng", "This room is both big and bright", "Adverbs", 3),

    # -- Week 4: Adverbs --
    _c("太", "tài", 4, "too; extremely; very", "太好了", "tài hǎo le", "That's great! / Too good!", "Adverbs", 4),
    _c("最", "zuì", 4, "most; -est (superlative)", "她是最好的老师", "tā shì zuì hǎo de lǎoshī", "She is the best teacher", "Adverbs", 4),
    _c("更", "gèng", 4, "more; even more", "今天比昨天更冷", "jīntiān bǐ zuótiān gèng lěng", "Today is even colder than yesterday", "Adverbs", 4),
    _c("比", "bǐ", 3, "to compare; than", "他比我高", "tā bǐ wǒ gāo", "He is taller than me", "Adverbs", 4),
    _c("非", "fēi", 1, "not; wrong; (非常=very)", "这个菜非常好吃", "zhè gè cài fēicháng hǎochī", "This dish is extremely delicious", "Adverbs", 4),
    _c("常", "cháng", 2, "often; frequently; normal", "我经常去公园", "wǒ jīngcháng qù gōngyuán", "I often go to the park", "Adverbs", 4),
    _c("以", "yǐ", 3, "by means of; so as to", "以后我要学中文", "yǐhòu wǒ yào xué zhōngwén", "In the future I want to study Chinese", "Function Words", 4),
    _c("从", "cóng", 2, "from; since; follow", "你从哪里来", "nǐ cóng nǎlǐ lái", "Where are you from?", "Function Words", 4),
    _c("于", "yú", 2, "at; in; to (formal)", "这本书关于中国历史", "zhè běn shū guānyú Zhōngguó lìshǐ", "This book is about Chinese history", "Function Words", 4),
    _c("为", "wèi", 4, "for; because of; in order to", "你为什么迟到了", "nǐ wèishénme chídào le", "Why were you late?", "Function Words", 4),
    _c("被", "bèi", 4, "passive marker (by); quilt", "他被老师批评了", "tā bèi lǎoshī pīpíng le", "He was criticized by the teacher", "Function Words", 4),
    _c("把", "bǎ", 3, "disposal marker; to take/hold", "把书放下", "bǎ shū fàng xià", "Put the book down", "Function Words", 4),

    # -- Week 5: Function Words --
    _c("给", "gěi", 3, "to give; for; to", "给我看", "gěi wǒ kàn", "Show me / Let me see", "Function Words", 5),
    _c("让", "ràng", 4, "to let; allow; to ask sb to", "让我来", "ràng wǒ lái", "Let me do it", "Function Words", 5),
    _c("向", "xiàng", 4, "toward; facing; direction", "向前走", "xiàng qián zǒu", "Walk forward", "Function Words", 5),
    _c("对", "duì", 4, "correct; toward; pair", "对不起", "duìbuqǐ", "Sorry; I'm sorry", "Function Words", 5),
    _c("着", "zhe", 5, "ongoing action particle (-ing)", "看着我", "kàn zhe wǒ", "Look at me (keep looking)", "Function Words", 5),
    _c("过", "guò", 4, "experience particle; to pass", "我去过中国", "wǒ qùguo Zhōngguó", "I've been to China", "Function Words", 5),
    _c("得", "de", 5, "complement marker (verb+得+adj)", "他跑得很快", "tā pǎo de hěn kuài", "He runs very fast", "Function Words", 5),
    _c("地", "de", 5, "adverb marker (adj+地+verb); ground", "她高兴地说谢谢", "tā gāoxìng de shuō xièxie", "She happily said thank you", "Function Words", 5),
    _c("其", "qí", 2, "its; his; that (其他=other)", "其他人都走了", "qítā rén dōu zǒu le", "Everyone else has left", "Function Words", 5),
    _c("所", "suǒ", 3, "place; (所以=therefore)", "我累了所以想休息", "wǒ lèi le suǒyǐ xiǎng xiūxi", "I am tired so I want to rest", "Function Words", 5),
    _c("而", "ér", 2, "and; but; yet (literary)", "他聪明而且努力", "tā cōngmíng érqiě nǔlì", "He is smart and also hardworking", "Function Words", 5),
    _c("或", "huò", 4, "or; perhaps; maybe", "你喝茶或者咖啡", "nǐ hē chá huòzhě kāfēi", "You can have tea or coffee", "Function Words", 5),

    # -- Week 6: Numbers --
    _c("一", "yī", 1, "one; a/an", "我有一个哥哥", "wǒ yǒu yī gè gēge", "I have one older brother", "Numbers", 6),
    _c("二", "èr", 4, "two", "他住在二楼", "tā zhù zài èr lóu", "He lives on the second floor", "Numbers", 6),
    _c("三", "sān", 1, "three", "我等了三天", "wǒ děng le sān tiān", "I waited for three days", "Numbers", 6),
    _c("四", "sì", 4, "four", "我四点钟下课", "wǒ sì diǎn zhōng xiàkè", "I finish class at four o'clock", "Numbers", 6),
    _c("五", "wǔ", 3, "five", "我买了五个苹果", "wǒ mǎi le wǔ gè píngguǒ", "I bought five apples", "Numbers", 6),
    _c("六", "liù", 4, "six", "我六月去北京", "wǒ liù yuè qù Běijīng", "I am going to Beijing in June", "Numbers", 6),
    _c("七", "qī", 1, "seven", "一周七天", "yī zhōu qī tiān", "7 days in a week", "Numbers", 6),
    _c("八", "bā", 1, "eight", "他八岁开始学钢琴", "tā bā suì kāishǐ xué gāngqín", "He started learning piano at age eight", "Numbers", 6),
    _c("九", "jiǔ", 3, "nine", "我九点上班", "wǒ jiǔ diǎn shàngbān", "I start work at nine o'clock", "Numbers", 6),
    _c("十", "shí", 2, "ten", "请等我十分钟", "qǐng děng wǒ shí fēnzhōng", "Please wait ten minutes for me", "Numbers", 6),
    _c("百", "bǎi", 3, "hundred", "这件衣服一百块", "zhè jiàn yīfu yī bǎi kuài", "This piece of clothing costs 100 yuan", "Numbers", 6),
    _c("千", "qiān", 1, "thousand", "这里有一千人", "zhèlǐ yǒu yī qiān rén", "There are one thousand people here", "Numbers", 6),

    # -- Week 7: Counting --
    _c("万", "wàn", 4, "ten thousand; myriad", "这辆车要十万元", "zhè liàng chē yào shí wàn yuán", "This car costs 100,000 yuan", "Counting", 7),
    _c("零", "líng", 2, "zero; remainder", "今天零下五度", "jīntiān líng xià wǔ dù", "Today it is five below zero", "Counting", 7),
    _c("两", "liǎng", 3, "two (with measure words); both", "我们两个人去吧", "wǒmen liǎng gè rén qù ba", "Let's go, the two of us", "Counting", 7),
    _c("几", "jǐ", 3, "how many; several", "你有几个孩子", "nǐ yǒu jǐ gè háizi", "How many children do you have?", "Counting", 7),
    _c("多", "duō", 1, "many; much; more", "这个多少钱", "zhè gè duōshǎo qián", "How much does this cost?", "Counting", 7),
    _c("少", "shǎo", 3, "few; little; scarce", "这里人很少", "zhèlǐ rén hěn shǎo", "There are very few people here", "Counting", 7),
    _c("个", "gè", 4, "general measure word", "我要一个苹果", "wǒ yào yī gè píngguǒ", "I want an apple", "Counting", 7),
    _c("些", "xiē", 1, "some; a few (plural marker)", "这些书是我的", "zhèxiē shū shì wǒ de", "These books are mine", "Counting", 7),
    _c("谁", "shuí", 2, "who; whom", "谁来了", "shuí lái le", "Who came?", "Question Words", 7),
    _c("哪", "nǎ", 3, "which; where (哪里=where)", "你去哪", "nǐ qù nǎ", "Where are you going?", "Question Words", 7),
    _c("怎", "zěn", 3, "how (怎么=how; 怎样=how)", "怎么办", "zěnme bàn", "What to do?", "Question Words", 7),
    _c("每", "měi", 3, "every; each", "我每天跑步", "wǒ měi tiān pǎobù", "I run every day", "Question Words", 7),

    # -- Week 8: People --
    _c("人", "rén", 2, "person; people; human", "那个人是我朋友", "nà gè rén shì wǒ péngyou", "That person is my friend", "People", 8),
    _c("家", "jiā", 1, "home; family; expert", "我想回家了", "wǒ xiǎng huí jiā le", "I want to go home now", "People", 8),
    _c("子", "zǐ", 3, "son; child; suffix", "孩子在玩", "háizi zài wán", "The children are playing", "People", 8),
    _c("女", "nǚ", 3, "woman; female; daughter", "我有一个女儿", "wǒ yǒu yí gè nǚér", "I have a daughter", "People", 8),
    _c("父", "fù", 4, "father (formal)", "父母很爱我", "fùmǔ hěn ài wǒ", "My parents love me very much", "People", 8),
    _c("母", "mǔ", 3, "mother (formal)", "母亲做饭了", "mǔqīn zuòfàn le", "Mother cooked a meal", "People", 8),
    _c("男", "nán", 2, "male; man; boy", "他是男生", "tā shì nánshēng", "He is a boy", "Family", 8),
    _c("兄", "xiōng", 1, "older brother (formal)", "我有两个兄弟", "wǒ yǒu liǎng gè xiōngdì", "I have two brothers", "Family", 8),
    _c("弟", "dì", 4, "younger brother", "弟弟在看书", "dìdi zài kàn shū", "My younger brother is reading", "Family", 8),
    _c("姐", "jiě", 3, "older sister", "姐姐很漂亮", "jiějie hěn piàoliang", "My older sister is very pretty", "Family", 8),
    _c("妹", "mèi", 4, "younger sister", "妹妹五岁了", "mèimei wǔ suì le", "My younger sister is five years old", "Family", 8),
    _c("友", "yǒu", 3, "friend; friendly", "他是我的朋友", "tā shì wǒ de péngyou", "He is my friend", "Family", 8),

    # -- Week 9: Family --
    _c("爸", "bà", 4, "dad; father (informal)", "爸爸在工作", "bàba zài gōngzuò", "Dad is working", "Family", 9),
    _c("妈", "mā", 1, "mom; mother (informal)", "妈妈很忙", "māma hěn máng", "Mom is very busy", "Family", 9),
    _c("哥", "gē", 1, "older brother (informal)", "哥哥在上学", "gēge zài shàngxué", "My older brother is at school", "Family", 9),
    _c("爷", "yé", 2, "grandfather (paternal)", "爷爷很高兴", "yéye hěn gāoxìng", "Grandpa is very happy", "Family", 9),
    _c("奶", "nǎi", 3, "grandmother (paternal); milk", "奶奶在做饭", "nǎinai zài zuòfàn", "Grandma is cooking", "Family", 9),
    _c("朋", "péng", 2, "friend (part of 朋友)", "朋友们都来了", "péngyoumen dōu lái le", "All the friends came", "Family", 9),
    _c("先", "xiān", 1, "first; before; mister (先生)", "王先生你好", "Wáng xiānsheng nǐ hǎo", "Hello, Mr. Wang", "Titles", 9),
    _c("生", "shēng", 1, "born; life; student; raw", "我是学生", "wǒ shì xuésheng", "I am a student", "Titles", 9),
    _c("老", "lǎo", 3, "old; elderly; always; very", "老师很好", "lǎoshī hěn hǎo", "The teacher is very nice", "Titles", 9),
    _c("师", "shī", 1, "teacher; master; expert", "老师好", "lǎoshī hǎo", "Hello, teacher!", "Titles", 9),
    _c("同", "tóng", 2, "same; together; with", "他是我同学", "tā shì wǒ tóngxué", "He is my classmate", "Titles", 9),
    _c("学", "xué", 2, "to study; to learn; school", "我在学中文", "wǒ zài xué Zhōngwén", "I am studying Chinese", "Titles", 9),

    # -- Week 10: People --
    _c("孩", "hái", 2, "child (孩子=child)", "小孩在笑", "xiǎohái zài xiào", "The little kid is laughing", "People", 10),
    _c("王", "wáng", 2, "king; (most common Chinese surname)", "王先生来了", "Wáng xiānsheng lái le", "Mr. Wang is here", "People", 10),
    _c("姓", "xìng", 4, "surname; to be surnamed", "您贵姓", "nín guì xìng", "What's your surname?", "People", 10),
    _c("名", "míng", 2, "name; fame; famous", "你叫什么名字", "nǐ jiào shénme míngzi", "What is your name?", "People", 10),
    _c("岁", "suì", 4, "years old; age", "你几岁", "nǐ jǐ suì", "How old are you?", "People", 10),
    _c("位", "wèi", 4, "polite measure word for people; seat", "这位是我妈妈", "zhè wèi shì wǒ māma", "This is my mom", "People", 10),
    _c("客", "kè", 4, "guest; visitor; customer", "客人来了", "kèrén lái le", "The guest has arrived", "People", 10),
    _c("叔", "shū", 1, "uncle (father's younger brother)", "叔叔在家吗", "shūshu zài jiā ma", "Is uncle at home?", "People", 10),
    _c("儿", "ér", 2, "son; child; suffix (儿化音)", "儿子很高", "érzi hěn gāo", "My son is very tall", "People", 10),
    _c("夫", "fū", 1, "husband; man (丈夫=husband)", "她的丈夫很好", "tā de zhàngfu hěn hǎo", "Her husband is very nice", "People", 10),
    _c("妻", "qī", 1, "wife", "他的妻子很美", "tā de qīzi hěn měi", "His wife is very beautiful", "People", 10),
    _c("您", "nín", 2, "you (polite/formal)", "您好，请问您贵姓", "nín hǎo, qǐngwèn nín guìxìng", "Hello, may I ask your surname?", "People", 10),

    # -- Week 11: Time --
    _c("年", "nián", 2, "year", "今年我二十岁", "jīnnián wǒ èrshí suì", "I am twenty years old this year", "Time", 11),
    _c("月", "yuè", 4, "month; moon", "这个月很忙", "zhège yuè hěn máng", "This month is very busy", "Time", 11),
    _c("日", "rì", 4, "day; sun; date", "今天是我的生日", "jīntiān shì wǒ de shēngrì", "Today is my birthday", "Time", 11),
    _c("天", "tiān", 1, "day; sky; heaven; weather", "今天很热", "jīntiān hěn rè", "Today is very hot", "Time", 11),
    _c("时", "shí", 2, "time; hour; when", "我等了一个小时", "wǒ děng le yí gè xiǎoshí", "I waited for one hour", "Time", 11),
    _c("今", "jīn", 1, "today; now; current", "今天天气好", "jīntiān tiānqì hǎo", "Nice weather today", "Time", 11),
    _c("明", "míng", 2, "tomorrow; bright; clear", "明天见", "míngtiān jiàn", "See you tomorrow", "Time", 11),
    _c("昨", "zuó", 2, "yesterday", "昨天下雨了", "zuótiān xiàyǔ le", "It rained yesterday", "Time", 11),
    _c("早", "zǎo", 3, "early; morning; Good morning!", "早上好", "zǎoshang hǎo", "Good morning!", "Time", 11),
    _c("晚", "wǎn", 3, "evening; late; night", "晚上好", "wǎnshang hǎo", "Good evening!", "Time", 11),
    _c("前", "qián", 2, "front; before; ago", "三天前他来了", "sān tiān qián tā lái le", "He came three days ago", "Time", 11),
    _c("后", "hòu", 4, "after; behind; later", "以后再说吧", "yǐhòu zài shuō ba", "Let's talk about it later", "Time", 11),

    # -- Week 12: Time --
    _c("分", "fēn", 1, "minute; to divide; part", "还有十分钟", "hái yǒu shí fēnzhōng", "There are still ten minutes", "Time", 12),
    _c("点", "diǎn", 3, "o'clock; dot; point; a little", "现在三点半", "xiànzài sān diǎn bàn", "It is 3:30 now", "Time", 12),
    _c("钟", "zhōng", 1, "clock; bell; minute (分钟)", "等我一分钟", "děng wǒ yī fēnzhōng", "Wait for me one minute", "Time", 12),
    _c("半", "bàn", 4, "half; semi-", "我等了半天", "wǒ děng le bàn tiān", "I waited for a long time", "Time", 12),
    _c("候", "hòu", 4, "to wait; time; season (时候)", "你什么时候来", "nǐ shénme shíhou lái", "When will you come?", "Time", 12),
    _c("刻", "kè", 4, "quarter-hour; to carve; moment", "还有一刻钟", "hái yǒu yī kè zhōng", "There are still fifteen minutes", "Time", 12),
    _c("周", "zhōu", 1, "week; to circle; Zhou (surname)", "上周我很忙", "shàng zhōu wǒ hěn máng", "I was very busy last week", "Time", 12),
    _c("期", "qī", 1, "period; phase (星期=week)", "今天是星期一", "jīntiān shì xīngqī yī", "Today is Monday", "Time", 12),
    _c("春", "chūn", 1, "spring (season)", "春天来了", "chūntiān lái le", "Spring has come", "Seasons", 12),
    _c("夏", "xià", 4, "summer", "夏天很热", "xiàtiān hěn rè", "Summer is very hot", "Seasons", 12),
    _c("秋", "qiū", 1, "autumn; fall", "秋天很美", "qiūtiān hěn měi", "Autumn is very beautiful", "Seasons", 12),
    _c("冬", "dōng", 1, "winter", "冬天很冷", "dōngtiān hěn lěng", "Winter is very cold", "Seasons", 12),

    # -- Week 13: Time --
    _c("节", "jié", 2, "festival; holiday; section", "春节快乐", "Chūn Jié kuàilè", "Happy Chinese New Year!", "Time", 13),
    _c("假", "jià", 4, "holiday; vacation; fake", "我们放假了", "wǒmen fàngjià le", "We are on holiday", "Time", 13),
    _c("久", "jiǔ", 3, "long (time); for a long time", "好久不见", "hǎo jiǔ bú jiàn", "Long time no see!", "Time", 13),
    _c("初", "chū", 1, "beginning; first; initial", "最初我不会", "zuìchū wǒ bú huì", "At first I could not do it", "Time", 13),
    _c("午", "wǔ", 3, "noon; midday", "下午我有课", "xiàwǔ wǒ yǒu kè", "I have class in the afternoon", "Time", 13),
    _c("现", "xiàn", 4, "now; present; current; to appear", "现在几点了", "xiànzài jǐ diǎn le", "What time is it now?", "Time", 13),

    # -- Week 14: Directions --
    _c("上", "shàng", 4, "up; above; on top; last (week)", "书在桌子上", "shū zài zhuōzi shàng", "The book is on the table", "Directions", 14),
    _c("下", "xià", 4, "down; below; under; next (week)", "猫在桌子下面", "māo zài zhuōzi xiàmiàn", "The cat is under the table", "Directions", 14),
    _c("左", "zuǒ", 3, "left", "请往左边走", "qǐng wǎng zuǒbiān zǒu", "Please go to the left", "Directions", 14),
    _c("右", "yòu", 4, "right", "学校在右边", "xuéxiào zài yòubiān", "The school is on the right", "Directions", 14),
    _c("中", "zhōng", 1, "middle; center; China", "他坐在中间", "tā zuò zài zhōngjiān", "He sits in the middle", "Directions", 14),
    _c("里", "lǐ", 3, "inside; in; within", "他在房间里", "tā zài fángjiān lǐ", "He is inside the room", "Directions", 14),
    _c("外", "wài", 4, "outside; foreign; other", "外面在下雨", "wàimiàn zài xiàyǔ", "It is raining outside", "Directions", 14),
    _c("东", "dōng", 1, "east", "太阳从东方来", "tàiyáng cóng dōngfāng lái", "The sun comes from the east", "Directions", 14),
    _c("西", "xī", 1, "west; (东西=thing)", "你买了什么东西", "nǐ mǎi le shénme dōngxi", "What things did you buy?", "Directions", 14),
    _c("南", "nán", 2, "south", "他住在南方", "tā zhù zài nánfāng", "He lives in the south", "Directions", 14),
    _c("北", "běi", 3, "north", "我想去北京", "wǒ xiǎng qù Běijīng", "I want to go to Beijing", "Directions", 14),
    _c("方", "fāng", 1, "direction; square; method", "这个地方很美", "zhège dìfang hěn měi", "This place is very beautiful", "Directions", 14),

    # -- Week 15: Location --
    _c("间", "jiān", 1, "between; room; space", "房间很大", "fángjiān hěn dà", "The room is very big", "Location", 15),
    _c("边", "biān", 1, "side; edge; (旁边=beside)", "他在我旁边", "tā zài wǒ pángbiān", "He is next to me", "Location", 15),
    _c("旁", "páng", 2, "beside; side; nearby", "学校在旁边", "xuéxiào zài pángbiān", "The school is nearby", "Location", 15),
    _c("近", "jìn", 4, "near; close", "学校离家很近", "xuéxiào lí jiā hěn jìn", "The school is very close to home", "Location", 15),
    _c("远", "yuǎn", 3, "far; distant; remote", "公司离这里很远", "gōngsī lí zhèlǐ hěn yuǎn", "The company is very far from here", "Location", 15),
    _c("面", "miàn", 4, "face; side; surface; noodles", "前面有一家店", "qiánmiàn yǒu yī jiā diàn", "There is a shop ahead", "Location", 15),

    # -- Week 16: Action Verbs --
    _c("来", "lái", 2, "to come", "请进来", "qǐng jìnlái", "Please come in", "Action Verbs", 16),
    _c("去", "qù", 4, "to go", "我去上学", "wǒ qù shàngxué", "I go to school", "Action Verbs", 16),
    _c("说", "shuō", 1, "to say; to speak; to tell", "他说中文", "tā shuō Zhōngwén", "He speaks Chinese", "Action Verbs", 16),
    _c("看", "kàn", 4, "to look; to watch; to read", "我们去看电影吧", "wǒmen qù kàn diànyǐng ba", "Let's go watch a movie", "Action Verbs", 16),
    _c("吃", "chī", 1, "to eat", "吃饭了吗", "chīfàn le ma", "Have you eaten?", "Action Verbs", 16),
    _c("喝", "hē", 1, "to drink", "我想喝茶", "wǒ xiǎng hē chá", "I want to drink tea", "Action Verbs", 16),
    _c("到", "dào", 4, "to arrive; to reach; until", "我到了", "wǒ dào le", "I've arrived", "Movement", 16),
    _c("出", "chū", 1, "to go out; to exit; to produce", "我们出去走走吧", "wǒmen chūqù zǒuzou ba", "Let's go out for a walk", "Movement", 16),
    _c("走", "zǒu", 3, "to walk; to leave; to go", "我们走吧", "wǒmen zǒu ba", "Let's go!", "Movement", 16),
    _c("开", "kāi", 1, "to open; to drive; to start", "请你开门", "qǐng nǐ kāi mén", "Please open the door", "Movement", 16),
    _c("回", "huí", 2, "to return; to go back; to reply", "我想回家", "wǒ xiǎng huí jiā", "I want to go home", "Movement", 16),
    _c("进", "jìn", 4, "to enter; to come/go in", "请进来坐吧", "qǐng jìn lái zuò ba", "Please come in and sit down", "Movement", 16),

    # -- Week 17: Action Verbs --
    _c("做", "zuò", 4, "to do; to make; to be", "妈妈在做饭", "māma zài zuòfàn", "Mom is cooking", "Action Verbs", 17),
    _c("用", "yòng", 4, "to use; with; useful", "我会用筷子", "wǒ huì yòng kuàizi", "I can use chopsticks", "Action Verbs", 17),
    _c("买", "mǎi", 3, "to buy; to purchase", "我去买菜", "wǒ qù mǎi cài", "I'm going to buy groceries", "Action Verbs", 17),
    _c("卖", "mài", 4, "to sell", "他在卖书", "tā zài mài shū", "He is selling books", "Action Verbs", 17),
    _c("找", "zhǎo", 3, "to find; to look for; to seek", "我在找人", "wǒ zài zhǎo rén", "I'm looking for someone", "Action Verbs", 17),
    _c("送", "sòng", 4, "to send; to give (a gift); to deliver", "他送我一个礼物", "tā sòng wǒ yí gè lǐwù", "He gave me a gift", "Action Verbs", 17),
    _c("打", "dǎ", 3, "to hit; to make (a call); to play", "我要打电话", "wǒ yào dǎ diànhuà", "I need to make a phone call", "Action Verbs", 17),
    _c("穿", "chuān", 1, "to wear; to put on; to pierce", "她穿了一件新衣服", "tā chuān le yí jiàn xīn yīfu", "She put on a new outfit", "Action Verbs", 17),
    _c("洗", "xǐ", 3, "to wash; to clean", "请先洗手", "qǐng xiān xǐ shǒu", "Please wash your hands first", "Action Verbs", 17),
    _c("换", "huàn", 4, "to change; to exchange; to swap", "我要换衣服", "wǒ yào huàn yīfu", "I need to change clothes", "Action Verbs", 17),
    _c("放", "fàng", 4, "to put; to place; to release; off (day)", "请把书放下", "qǐng bǎ shū fàng xià", "Please put the book down", "Action Verbs", 17),
    _c("拿", "ná", 2, "to take; to hold; to carry", "请你拿来", "qǐng nǐ ná lái", "Please bring it here", "Action Verbs", 17),

    # -- Week 18: Movement --
    _c("跑", "pǎo", 3, "to run", "他每天跑步", "tā měitiān pǎobù", "He runs every day", "Movement", 18),
    _c("飞", "fēi", 1, "to fly", "飞机飞得很快", "fēijī fēi de hěn kuài", "The airplane flies very fast", "Movement", 18),
    _c("游", "yóu", 2, "to swim; to travel; to tour", "我喜欢游泳", "wǒ xǐhuan yóuyǒng", "I like to swim", "Movement", 18),
    _c("爬", "pá", 2, "to climb; to crawl", "我们去爬山吧", "wǒmen qù pá shān ba", "Let's go climb a mountain", "Movement", 18),
    _c("站", "zhàn", 4, "to stand; station; stop", "请大家站起来", "qǐng dàjiā zhàn qǐlái", "Please everyone stand up", "Movement", 18),
    _c("坐", "zuò", 4, "to sit; to take (bus/train)", "请坐下吧", "qǐng zuò xià ba", "Please sit down", "Movement", 18),
    _c("听", "tīng", 1, "to listen; to hear", "我喜欢听音乐", "wǒ xǐhuan tīng yīnyuè", "I like listening to music", "Communication", 18),
    _c("问", "wèn", 4, "to ask; to inquire", "我想问一个问题", "wǒ xiǎng wèn yí gè wèntí", "I want to ask a question", "Communication", 18),
    _c("答", "dá", 2, "to answer; to reply", "请你回答我的问题", "qǐng nǐ huídá wǒ de wèntí", "Please answer my question", "Communication", 18),
    _c("叫", "jiào", 4, "to call; to be called; to order", "我叫小明", "wǒ jiào Xiǎo Míng", "My name is Xiao Ming", "Communication", 18),
    _c("请", "qǐng", 3, "please; to invite; to treat", "请问你是哪国人", "qǐngwèn nǐ shì nǎ guó rén", "May I ask what country you are from?", "Communication", 18),
    _c("住", "zhù", 4, "to live; to stay; to reside", "我住在北京", "wǒ zhù zài Běijīng", "I live in Beijing", "Communication", 18),

    # -- Week 19: Action Verbs --
    _c("带", "dài", 4, "to bring; to carry; to wear (belt)", "请把书带来", "qǐng bǎ shū dài lái", "Please bring the book", "Action Verbs", 19),
    _c("拉", "lā", 1, "to pull; to drag; to play (violin)", "请拉开门", "qǐng lā kāi mén", "Please pull the door open", "Action Verbs", 19),
    _c("推", "tuī", 1, "to push; to postpone", "他推开了门", "tā tuī kāi le mén", "He pushed the door open", "Action Verbs", 19),
    _c("搬", "bān", 1, "to move (house/objects)", "我下个月搬家", "wǒ xià gè yuè bān jiā", "I am moving house next month", "Action Verbs", 19),
    _c("举", "jǔ", 3, "to raise; to lift; to hold up", "请举手回答", "qǐng jǔ shǒu huídá", "Please raise your hand to answer", "Action Verbs", 19),
    _c("接", "jiē", 1, "to receive; to pick up; to connect", "请你接电话", "qǐng nǐ jiē diànhuà", "Please answer the phone", "Action Verbs", 19),

    # -- Week 20: Cognitive --
    _c("想", "xiǎng", 3, "to think; to want; to miss", "我想你", "wǒ xiǎng nǐ", "I miss you", "Cognitive", 20),
    _c("知", "zhī", 1, "to know (a fact); knowledge", "我不知道", "wǒ bù zhīdào", "I don't know", "Cognitive", 20),
    _c("道", "dào", 4, "road; way; to say; (知道=know)", "知道了", "zhīdào le", "Got it / I know now", "Cognitive", 20),
    _c("认", "rèn", 4, "to recognize; to know (a person)", "我认识他", "wǒ rènshi tā", "I know him", "Cognitive", 20),
    _c("识", "shí", 2, "to know; knowledge; to recognize", "认识你很高兴", "rènshi nǐ hěn gāoxìng", "Nice to meet you", "Cognitive", 20),
    _c("觉", "jué", 2, "to feel; to sense; sleep (睡觉)", "我感觉很累", "wǒ gǎnjué hěn lèi", "I feel very tired", "Cognitive", 20),
    _c("记", "jì", 4, "to remember; to record; to note", "你要记住这个", "nǐ yào jì zhù zhège", "You need to remember this", "Learning", 20),
    _c("懂", "dǒng", 3, "to understand", "听懂了", "tīng dǒng le", "Understood (by listening)", "Learning", 20),
    _c("念", "niàn", 4, "to read aloud; to miss; to study", "他在念书", "tā zài niàn shū", "He is studying", "Learning", 20),
    _c("忘", "wàng", 4, "to forget", "别忘了", "bié wàng le", "Don't forget!", "Learning", 20),
    _c("思", "sī", 1, "to think; thought; to miss", "这个词是什么意思", "zhège cí shì shénme yìsi", "What does this word mean?", "Learning", 20),
    _c("决", "jué", 2, "to decide; to determine", "我已经决定了", "wǒ yǐjīng juédìng le", "I have already decided", "Learning", 20),

    # -- Week 21: Education --
    _c("读", "dú", 2, "to read; to study; reading", "我每天读书", "wǒ měitiān dú shū", "I read every day", "Education", 21),
    _c("写", "xiě", 3, "to write", "他在写字", "tā zài xiě zì", "He is writing characters", "Education", 21),
    _c("教", "jiāo", 1, "to teach; to instruct", "她教我们中文", "tā jiāo wǒmen Zhōngwén", "She teaches us Chinese", "Education", 21),
    _c("习", "xí", 2, "to practice; habit (学习=study)", "我每天学习中文", "wǒ měitiān xuéxí Zhōngwén", "I study Chinese every day", "Education", 21),
    _c("考", "kǎo", 3, "to test; exam; to examine", "明天有考试", "míngtiān yǒu kǎoshì", "There is an exam tomorrow", "Education", 21),
    _c("试", "shì", 4, "to try; test; exam (考试)", "你试试吧", "nǐ shìshi ba", "Give it a try", "Education", 21),
    _c("选", "xuǎn", 3, "to choose; to select; to elect", "你选择哪个", "nǐ xuǎnzé nǎge", "Which one do you choose?", "Education", 21),
    _c("择", "zé", 2, "to choose; to pick; to select", "这是一道选择题", "zhè shì yí dào xuǎnzé tí", "This is a multiple choice question", "Education", 21),
    _c("注", "zhù", 4, "to note; to pay attention; to pour", "请注意安全", "qǐng zhùyì ānquán", "Please pay attention to safety", "Education", 21),
    _c("意", "yì", 4, "meaning; intention; idea", "这本书很有意思", "zhè běn shū hěn yǒu yìsi", "This book is very interesting", "Education", 21),
    _c("告", "gào", 4, "to tell; to inform; to announce", "我告诉你一件事", "wǒ gàosu nǐ yí jiàn shì", "Let me tell you something", "Education", 21),
    _c("诉", "sù", 4, "to tell; to inform; to complain", "请告诉我怎么走", "qǐng gàosu wǒ zěnme zǒu", "Please tell me how to get there", "Education", 21),

    # -- Week 22: Adjectives --
    _c("大", "dà", 4, "big; large; great", "这个大学很大", "zhège dàxué hěn dà", "This university is very big", "Adjectives", 22),
    _c("小", "xiǎo", 3, "small; little; young", "过马路要小心", "guò mǎlù yào xiǎoxīn", "Be careful when crossing the street", "Adjectives", 22),
    _c("好", "hǎo", 3, "good; well; OK", "今天天气真好", "jīntiān tiānqì zhēn hǎo", "The weather is really nice today", "Adjectives", 22),
    _c("坏", "huài", 4, "bad; broken; spoiled", "手机坏了", "shǒujī huài le", "Phone is broken", "Adjectives", 22),
    _c("新", "xīn", 1, "new; fresh", "新年快乐", "xīnnián kuàilè", "Happy New Year!", "Adjectives", 22),
    _c("旧", "jiù", 4, "old; used; worn; former", "这是一本旧书", "zhè shì yì běn jiù shū", "This is a used book", "Adjectives", 22),
    _c("长", "cháng", 2, "long (length/time)", "我等了很长时间", "wǒ děng le hěn cháng shíjiān", "I waited a very long time", "Adjectives", 22),
    _c("短", "duǎn", 3, "short (length/time)", "时间太短", "shíjiān tài duǎn", "too little time", "Adjectives", 22),
    _c("高", "gāo", 1, "tall; high; loud", "他很高", "tā hěn gāo", "He is very tall", "Adjectives", 22),
    _c("低", "dī", 1, "low; short (height)", "声音太低", "shēngyīn tài dī", "voice too low", "Adjectives", 22),
    _c("快", "kuài", 4, "fast; quick; soon; happy", "你快来吧", "nǐ kuài lái ba", "Come quickly!", "Adjectives", 22),
    _c("慢", "màn", 4, "slow; slowly", "慢慢来", "mànmàn lái", "Take your time", "Adjectives", 22),

    # -- Week 23: Adjectives --
    _c("热", "rè", 4, "hot; warm; popular", "今天很热", "jīntiān hěn rè", "It's hot today", "Adjectives", 23),
    _c("冷", "lěng", 3, "cold; cool; indifferent", "外面很冷", "wàimiàn hěn lěng", "It's cold outside", "Adjectives", 23),
    _c("干", "gān", 1, "dry; clean; to do (干=gàn)", "这个房间很干净", "zhège fángjiān hěn gānjìng", "This room is very clean", "Adjectives", 23),
    _c("净", "jìng", 4, "clean; pure; only", "你的衣服不干净", "nǐ de yīfu bù gānjìng", "Your clothes are not clean", "Adjectives", 23),
    _c("难", "nán", 2, "difficult; hard; unpleasant", "这个问题很难", "zhège wèntí hěn nán", "This question is very difficult", "Adjectives", 23),
    _c("易", "yì", 4, "easy; simple (容易=easy)", "中文不容易学", "Zhōngwén bù róngyì xué", "Chinese is not easy to learn", "Adjectives", 23),
    _c("贵", "guì", 4, "expensive; noble; your (polite)", "太贵了", "tài guì le", "Too expensive!", "Adjectives", 23),
    _c("胖", "pàng", 4, "fat; plump; chubby", "我最近胖了", "wǒ zuìjìn pàng le", "I have gained weight recently", "Adjectives", 23),
    _c("瘦", "shòu", 4, "thin; skinny; lean", "她比以前瘦了", "tā bǐ yǐqián shòu le", "She is thinner than before", "Adjectives", 23),
    _c("饿", "è", 4, "hungry", "我饿了", "wǒ è le", "I'm hungry", "Adjectives", 23),
    _c("渴", "kě", 3, "thirsty", "我渴了", "wǒ kě le", "I'm thirsty", "Adjectives", 23),
    _c("满", "mǎn", 3, "full; filled; satisfied", "我很满意", "wǒ hěn mǎnyì", "I am very satisfied", "Adjectives", 23),

    # -- Week 24: Adjectives --
    _c("亮", "liàng", 4, "bright; shiny; clear", "她很漂亮", "tā hěn piàoliang", "She is very beautiful", "Adjectives", 24),
    _c("美", "měi", 3, "beautiful; fine; America", "这里的风景很美丽", "zhèlǐ de fēngjǐng hěn měilì", "The scenery here is beautiful", "Adjectives", 24),
    _c("丑", "chǒu", 3, "ugly; shameful", "这只猫很丑", "zhè zhī māo hěn chǒu", "This cat is very ugly", "Adjectives", 24),
    _c("忙", "máng", 2, "busy; hurried", "我很忙", "wǒ hěn máng", "I'm very busy", "Adjectives", 24),
    _c("累", "lèi", 4, "tired; weary; tiring", "我今天很累", "wǒ jīntiān hěn lèi", "I am very tired today", "Adjectives", 24),
    _c("安", "ān", 1, "safe; peaceful; calm; to install", "这里很安全", "zhèlǐ hěn ānquán", "It is safe here", "Adjectives", 24),
    _c("静", "jìng", 4, "quiet; calm; still", "请安静一下", "qǐng ānjìng yīxià", "Please be quiet for a moment", "Adjectives", 24),
    _c("简", "jiǎn", 3, "simple; brief; to simplify", "这个很简单", "zhège hěn jiǎndān", "This is very simple", "Adjectives", 24),
    _c("单", "dān", 1, "single; simple; alone; list", "这道题很简单", "zhè dào tí hěn jiǎndān", "This question is very simple", "Adjectives", 24),
    _c("清", "qīng", 1, "clear; clean; pure; Qing dynasty", "我听清楚了", "wǒ tīng qīngchu le", "I heard it clearly", "Adjectives", 24),
    _c("楚", "chǔ", 3, "clear; tidy (清楚=clear)", "他说得清清楚楚", "tā shuō de qīngqīng chǔchǔ", "He said it crystal clear", "Adjectives", 24),
    _c("整", "zhěng", 3, "whole; entire; to arrange; neat", "他整天都在学习", "tā zhěng tiān dōu zài xuéxí", "He studies all day long", "Adjectives", 24),

    # -- Week 25: Colors --
    _c("红", "hóng", 2, "red; popular; lucky", "她穿了一件红色的衣服", "tā chuānle yī jiàn hóngsè de yīfu", "She wore a red piece of clothing", "Colors", 25),
    _c("白", "bái", 2, "white; plain; blank; in vain", "那只猫是白色的", "nà zhī māo shì báisè de", "That cat is white", "Colors", 25),
    _c("黑", "hēi", 1, "black; dark", "天黑了", "tiān hēi le", "It got dark", "Colors", 25),
    _c("蓝", "lán", 2, "blue", "今天的蓝天很美", "jīntiān de lán tiān hěn měi", "Today's blue sky is beautiful", "Colors", 25),
    _c("绿", "lǜ", 4, "green", "树叶是绿色的", "shùyè shì lǜsè de", "The leaves are green", "Colors", 25),
    _c("黄", "huáng", 2, "yellow", "这朵花是黄色的", "zhè duǒ huā shì huángsè de", "This flower is yellow", "Colors", 25),
    _c("水", "shuǐ", 3, "water", "我想喝水", "wǒ xiǎng hē shuǐ", "I want to drink water", "Nature", 25),
    _c("火", "huǒ", 3, "fire; flame; angry", "我坐火车去北京", "wǒ zuò huǒchē qù Běijīng", "I take the train to Beijing", "Nature", 25),
    _c("山", "shān", 1, "mountain; hill", "我们去爬山吧", "wǒmen qù pá shān ba", "Let's go climb a mountain", "Nature", 25),
    _c("木", "mù", 4, "wood; tree; wooden", "这张桌子是木头做的", "zhè zhāng zhuōzi shì mùtou zuò de", "This table is made of wood", "Nature", 25),
    _c("土", "tǔ", 3, "earth; soil; land; local", "这块土地很大", "zhè kuài tǔdì hěn dà", "This piece of land is very big", "Nature", 25),
    _c("花", "huā", 1, "flower; to spend (money/time)", "我给妈妈买花了", "wǒ gěi māma mǎi huā le", "I bought flowers for Mom", "Nature", 25),

    # -- Week 26: Nature --
    _c("草", "cǎo", 3, "grass; plant; rough", "孩子们在草地上玩", "háizimen zài cǎodì shàng wán", "The children are playing on the grass", "Nature", 26),
    _c("树", "shù", 4, "tree", "树上有鸟", "shù shàng yǒu niǎo", "Birds in the tree", "Nature", 26),
    _c("雨", "yǔ", 3, "rain", "下雨了", "xià yǔ le", "It's raining", "Weather", 26),
    _c("风", "fēng", 1, "wind; style; custom", "今天风很大", "jīntiān fēng hěn dà", "The wind is strong today", "Weather", 26),
    _c("雪", "xuě", 3, "snow", "下雪了", "xià xuě le", "It's snowing", "Weather", 26),
    _c("云", "yún", 2, "cloud", "天上有白云", "tiān shàng yǒu báiyún", "There are white clouds in the sky", "Weather", 26),
    _c("河", "hé", 2, "river", "这条河的水很清", "zhè tiáo hé de shuǐ hěn qīng", "The water in this river is very clear", "Nature", 26),
    _c("海", "hǎi", 3, "sea; ocean", "我想去看大海", "wǒ xiǎng qù kàn dà hǎi", "I want to go see the ocean", "Nature", 26),
    _c("叶", "yè", 4, "leaf", "树叶变黄了", "shùyè biàn huáng le", "The leaves have turned yellow", "Nature", 26),
    _c("阳", "yáng", 2, "sun; solar; positive; male", "太阳出来了", "tàiyáng chūlái le", "The sun has come out", "Nature", 26),
    _c("阴", "yīn", 1, "cloudy; overcast; shade; lunar", "今天是阴天", "jīntiān shì yīn tiān", "Today is a cloudy day", "Weather", 26),
    _c("晴", "qíng", 2, "clear; sunny (weather)", "明天是晴天", "míngtiān shì qíng tiān", "Tomorrow will be sunny", "Weather", 26),

    # -- Week 27: Nature --
    _c("鸟", "niǎo", 3, "bird", "一只小鸟在唱歌", "yī zhī xiǎo niǎo zài chànggē", "A little bird is singing", "Nature", 27),
    _c("石", "shí", 2, "stone; rock", "路上有一块石头", "lù shàng yǒu yī kuài shítou", "There is a stone on the road", "Nature", 27),
    _c("景", "jǐng", 3, "scenery; view; scene", "这里的风景很美", "zhèlǐ de fēngjǐng hěn měi", "The scenery here is beautiful", "Nature", 27),
    _c("环", "huán", 2, "ring; loop; (环境=environment)", "我们要保护环境", "wǒmen yào bǎohù huánjìng", "We should protect the environment", "Nature", 27),
    _c("境", "jìng", 4, "border; territory; environment", "这里的环境很好", "zhèlǐ de huánjìng hěn hǎo", "The environment here is nice", "Nature", 27),
    _c("气", "qì", 4, "air; gas; energy; angry; weather", "今天天气很好", "jīntiān tiānqì hěn hǎo", "The weather is nice today", "Nature", 27),
    _c("手", "shǒu", 3, "hand; expert at sth", "请先洗手", "qǐng xiān xǐ shǒu", "Please wash your hands first", "Body", 27),
    _c("口", "kǒu", 3, "mouth; opening; entrance", "入口在那边", "rùkǒu zài nàbiān", "The entrance is over there", "Body", 27),
    _c("眼", "yǎn", 3, "eye", "她的眼睛很大", "tā de yǎnjing hěn dà", "Her eyes are very big", "Body", 27),
    _c("耳", "ěr", 3, "ear", "他的耳朵很小", "tā de ěrduo hěn xiǎo", "His ears are very small", "Body", 27),
    _c("心", "xīn", 1, "heart; mind; center", "过马路要小心", "guò mǎlù yào xiǎoxīn", "Be careful when crossing the street", "Body", 27),
    _c("头", "tóu", 2, "head; top; first", "我头疼", "wǒ tóuténg", "I have a headache", "Body", 27),

    # -- Week 28: Body --
    _c("脚", "jiǎo", 3, "foot", "我的脚疼", "wǒ de jiǎo téng", "My foot hurts", "Body", 28),
    _c("身", "shēn", 1, "body; oneself", "他的身体很好", "tā de shēntǐ hěn hǎo", "He is in good health", "Body", 28),
    _c("背", "bèi", 4, "back; to carry; to memorize", "我背了一个背包", "wǒ bēile yī gè bēibāo", "I carried a backpack", "Body", 28),
    _c("腿", "tuǐ", 3, "leg", "她的腿很长", "tā de tuǐ hěn cháng", "Her legs are very long", "Body", 28),
    _c("鼻", "bí", 2, "nose", "他的鼻子很高", "tā de bízi hěn gāo", "His nose is very tall", "Body", 28),
    _c("嘴", "zuǐ", 3, "mouth; lips", "她的嘴巴很小", "tā de zuǐba hěn xiǎo", "Her mouth is very small", "Body", 28),
    _c("病", "bìng", 4, "sick; illness; disease", "他生病了", "tā shēng bìng le", "He got sick", "Health", 28),
    _c("药", "yào", 4, "medicine; drug; cure", "你要按时吃药", "nǐ yào ànshí chī yào", "You should take medicine on time", "Health", 28),
    _c("疼", "téng", 2, "painful; to ache; to love dearly", "我的头很疼", "wǒ de tóu hěn téng", "My head really hurts", "Health", 28),
    _c("体", "tǐ", 3, "body; form; style; substance", "爷爷的身体很好", "yéye de shēntǐ hěn hǎo", "Grandpa is in good health", "Health", 28),
    _c("医", "yī", 1, "medicine; medical; doctor", "她是一位医生", "tā shì yī wèi yīshēng", "She is a doctor", "Health", 28),
    _c("院", "yuàn", 4, "courtyard; institution; hospital", "他去医院了", "tā qù yīyuàn le", "He went to the hospital", "Health", 28),

    # -- Week 29: Food --
    _c("饭", "fàn", 4, "cooked rice; meal; food", "我们一起吃饭吧", "wǒmen yīqǐ chīfàn ba", "Let's eat together", "Food", 29),
    _c("茶", "chá", 2, "tea", "爸爸喜欢喝茶", "bàba xǐhuan hē chá", "Dad likes to drink tea", "Food", 29),
    _c("酒", "jiǔ", 3, "alcohol; wine; liquor", "他不喝酒", "tā bù hē jiǔ", "He doesn't drink alcohol", "Food", 29),
    _c("米", "mǐ", 3, "rice (uncooked); meter", "我要一碗米饭", "wǒ yào yī wǎn mǐfàn", "I want a bowl of rice", "Food", 29),
    _c("肉", "ròu", 4, "meat; flesh", "我不吃猪肉", "wǒ bù chī zhūròu", "I don't eat pork", "Food", 29),
    _c("菜", "cài", 4, "vegetable; dish; food", "我喜欢吃中国菜", "wǒ xǐhuan chī Zhōngguó cài", "I like eating Chinese food", "Food", 29),
    _c("鸡", "jī", 1, "chicken", "这个鸡肉很好吃", "zhège jīròu hěn hǎochī", "This chicken is delicious", "Food", 29),
    _c("蛋", "dàn", 4, "egg", "我早上吃了一个鸡蛋", "wǒ zǎoshang chīle yī gè jīdàn", "I ate an egg this morning", "Food", 29),
    _c("豆", "dòu", 4, "bean; pea; legume", "我喜欢吃豆腐", "wǒ xǐhuan chī dòufu", "I like eating tofu", "Food", 29),
    _c("果", "guǒ", 3, "fruit; result", "多吃水果对身体好", "duō chī shuǐguǒ duì shēntǐ hǎo", "Eating more fruit is good for your health", "Food", 29),
    _c("糖", "táng", 2, "sugar; candy; sweet", "小孩子喜欢吃糖果", "xiǎo háizi xǐhuan chī tángguǒ", "Children like eating candy", "Food", 29),
    _c("牛", "niú", 2, "cow; cattle; ox; stubborn", "我想吃牛肉", "wǒ xiǎng chī niúròu", "I want to eat beef", "Food", 29),

    # -- Week 30: Food --
    _c("羊", "yáng", 2, "sheep; goat; lamb", "这家店的羊肉很好吃", "zhè jiā diàn de yángròu hěn hǎochī", "This restaurant's lamb is delicious", "Food", 30),
    _c("苹", "píng", 2, "apple (part of 苹果)", "我买了几个苹果", "wǒ mǎile jǐ gè píngguǒ", "I bought a few apples", "Food", 30),
    _c("杯", "bēi", 1, "cup; glass; (measure word)", "请给我一杯茶", "qǐng gěi wǒ yī bēi chá", "Please give me a cup of tea", "Food", 30),
    _c("碗", "wǎn", 3, "bowl", "我吃了一碗饭", "wǒ chīle yī wǎn fàn", "I ate a bowl of rice", "Food", 30),
    _c("瓶", "píng", 2, "bottle", "我买了一瓶水", "wǒ mǎile yī píng shuǐ", "I bought a bottle of water", "Food", 30),
    _c("盘", "pán", 2, "plate; dish; tray", "桌上有一盘菜", "zhuō shàng yǒu yī pán cài", "There is a plate of food on the table", "Food", 30),
    _c("衣", "yī", 1, "clothing; garment (衣服=clothes)", "这件衣服很好看", "zhè jiàn yīfu hěn hǎokàn", "This piece of clothing looks great", "Clothing", 30),
    _c("服", "fú", 2, "clothing; to serve; to obey", "她在穿衣服", "tā zài chuān yīfu", "She is getting dressed", "Clothing", 30),
    _c("鞋", "xié", 2, "shoes", "请穿鞋进来", "qǐng chuān xié jìnlái", "Please put on shoes before coming in", "Clothing", 30),
    _c("帽", "mào", 4, "hat; cap", "他戴了一顶帽子", "tā dàile yī dǐng màozi", "He is wearing a hat", "Clothing", 30),
    _c("裤", "kù", 4, "pants; trousers", "这条裤子太长了", "zhè tiáo kùzi tài cháng le", "These pants are too long", "Clothing", 30),
    _c("裙", "qún", 2, "skirt; dress", "她穿了一条裙子", "tā chuānle yī tiáo qúnzi", "She is wearing a skirt", "Clothing", 30),

    # -- Week 31: Home --
    _c("房", "fáng", 2, "house; room; building", "我的房间很大", "wǒ de fángjiān hěn dà", "My room is very big", "Home", 31),
    _c("门", "mén", 2, "door; gate; entrance", "请开门", "qǐng kāi mén", "Please open the door", "Home", 31),
    _c("窗", "chuāng", 1, "window", "窗户开着呢", "chuānghù kāi zhe ne", "The window is open", "Home", 31),
    _c("桌", "zhuō", 1, "table; desk", "桌子上有一本书", "zhuōzi shàng yǒu yī běn shū", "There is a book on the table", "Home", 31),
    _c("椅", "yǐ", 3, "chair", "请坐这把椅子", "qǐng zuò zhè bǎ yǐzi", "Please sit in this chair", "Home", 31),
    _c("床", "chuáng", 2, "bed", "我要上床睡觉了", "wǒ yào shàng chuáng shuìjiào le", "I'm going to bed now", "Home", 31),
    _c("灯", "dēng", 1, "light; lamp", "请把灯开了", "qǐng bǎ dēng kāi le", "Please turn on the light", "Home", 31),
    _c("楼", "lóu", 2, "floor; story; building", "我住在一楼", "wǒ zhù zài yī lóu", "I live on the first floor", "Home", 31),
    _c("层", "céng", 2, "floor (measure word); layer", "这栋楼有三层", "zhè dòng lóu yǒu sān céng", "This building has three floors", "Home", 31),
    _c("厨", "chú", 2, "kitchen (厨房=kitchen)", "妈妈在厨房做饭", "māma zài chúfáng zuòfàn", "Mom is cooking in the kitchen", "Home", 31),
    _c("刀", "dāo", 1, "knife; blade", "这把小刀很快", "zhè bǎ xiǎo dāo hěn kuài", "This small knife is very sharp", "Home", 31),
    _c("伞", "sǎn", 3, "umbrella", "今天要带伞吗", "jīntiān yào dài sǎn ma", "Do I need to bring an umbrella today?", "Home", 31),

    # -- Week 32: Transport --
    _c("车", "chē", 1, "vehicle; car; train", "我们坐车去吧", "wǒmen zuò chē qù ba", "Let's go by car", "Transport", 32),
    _c("路", "lù", 4, "road; path; route", "一路平安", "yī lù píng'ān", "Safe journey!", "Transport", 32),
    _c("城", "chéng", 2, "city; town; wall", "这个城市很美", "zhège chéngshì hěn měi", "This city is very beautiful", "Transport", 32),
    _c("店", "diàn", 4, "shop; store; inn", "我想去书店", "wǒ xiǎng qù shūdiàn", "I want to go to the bookstore", "Transport", 32),
    _c("市", "shì", 4, "city; market; urban", "我去超市买菜", "wǒ qù chāoshì mǎi cài", "I'm going to the supermarket to buy groceries", "Transport", 32),
    _c("街", "jiē", 1, "street; road", "我们去逛街吧", "wǒmen qù guàng jiē ba", "Let's go shopping", "Transport", 32),
    _c("船", "chuán", 2, "boat; ship", "我没坐过船", "wǒ méi zuò guo chuán", "I've never taken a boat", "Transport", 32),
    _c("票", "piào", 4, "ticket; ballot; note", "我要买两张票", "wǒ yào mǎi liǎng zhāng piào", "I want to buy two tickets", "Transport", 32),
    _c("租", "zū", 1, "to rent; to hire", "我们打出租车吧", "wǒmen dǎ chūzūchē ba", "Let's take a taxi", "Transport", 32),
    _c("场", "chǎng", 3, "field; ground; venue; site", "机场离这里很远", "jīchǎng lí zhèlǐ hěn yuǎn", "The airport is far from here", "Transport", 32),
    _c("公", "gōng", 1, "public; male; official; fair", "我坐公共汽车上班", "wǒ zuò gōnggòng qìchē shàngbān", "I take the bus to work", "Transport", 32),
    _c("司", "sī", 1, "to manage; department (公司=company)", "他在公司上班", "tā zài gōngsī shàngbān", "He works at a company", "Transport", 32),

    # -- Week 33: Places --
    _c("旅", "lǚ", 3, "to travel; trip; journey", "我喜欢旅游", "wǒ xǐhuān lǚyóu", "I like traveling", "Places", 33),
    _c("铁", "tiě", 3, "iron; hard (地铁=subway)", "我坐地铁去上班", "wǒ zuò dìtiě qù shàngbān", "I take the subway to work", "Places", 33),
    _c("桥", "qiáo", 2, "bridge", "我们要过桥", "wǒmen yào guò qiáo", "We need to cross the bridge", "Places", 33),
    _c("运", "yùn", 4, "to transport; luck; fate", "他每天运动", "tā měitiān yùndòng", "He exercises every day", "Places", 33),
    _c("动", "dòng", 4, "to move; action; movement", "我喜欢运动", "wǒ xǐhuān yùndòng", "I like exercising", "Places", 33),
    _c("步", "bù", 4, "step; pace; foot; to walk", "她每天跑步", "tā měitiān pǎobù", "She jogs every day", "Places", 33),
    _c("校", "xiào", 4, "school", "我的学校很大", "wǒ de xuéxiào hěn dà", "My school is very big", "Places", 33),
    _c("馆", "guǎn", 3, "hall; building; hotel; restaurant", "图书馆在那边", "túshūguǎn zài nàbiān", "The library is over there", "Places", 33),
    _c("宾", "bīn", 1, "guest (宾馆=hotel)", "我住在宾馆里", "wǒ zhù zài bīnguǎn lǐ", "I'm staying at a hotel", "Places", 33),
    _c("办", "bàn", 4, "to do; to handle; to manage", "他在办公室工作", "tā zài bàngōngshì gōngzuò", "He works in the office", "Places", 33),
    _c("园", "yuán", 2, "garden; park; yard", "我们去公园吧", "wǒmen qù gōngyuán ba", "Let's go to the park", "Places", 33),
    _c("商", "shāng", 1, "business; commerce; merchant", "商店几点关门", "shāngdiàn jǐ diǎn guānmén", "What time does the shop close?", "Places", 33),

    # -- Week 34: Places --
    _c("村", "cūn", 1, "village", "他住在农村", "tā zhù zài nóngcūn", "He lives in the countryside", "Places", 34),
    _c("区", "qū", 1, "area; district; zone", "这个小区很安静", "zhège xiǎoqū hěn ānjìng", "This residential area is very quiet", "Places", 34),
    _c("世", "shì", 4, "world; era; generation (世界)", "世界很大", "shìjiè hěn dà", "The world is very big", "Places", 34),
    _c("界", "jiè", 4, "boundary; world; field", "我想看看世界", "wǒ xiǎng kànkan shìjiè", "I want to see the world", "Places", 34),
    _c("京", "jīng", 1, "capital (city); Beijing", "我去过北京", "wǒ qù guo Běijīng", "I've been to Beijing", "Places", 34),
    _c("国", "guó", 2, "country; nation; national", "中国很大", "Zhōngguó hěn dà", "China is very big", "Places", 34),
    _c("银", "yín", 2, "silver; money; bank (银行)", "银行在哪里", "yínháng zài nǎlǐ", "Where is the bank?", "Places", 34),
    _c("行", "xíng", 2, "to walk; OK; bank (银行=yínháng)", "行不行", "xíng bu xíng", "Is that OK?", "Places", 34),
    _c("室", "shì", 4, "room; office; studio", "学生在教室里", "xuéshēng zài jiàoshì lǐ", "The students are in the classroom", "Places", 34),
    _c("图", "tú", 2, "picture; map; drawing; plan", "你有地图吗", "nǐ yǒu dìtú ma", "Do you have a map?", "Places", 34),
    _c("广", "guǎng", 3, "wide; broad; extensive", "广场上人很多", "guǎngchǎng shàng rén hěn duō", "There are many people in the plaza", "Places", 34),

    # -- Week 35: Education --
    _c("课", "kè", 4, "class; lesson; course", "我们九点上课", "wǒmen jiǔ diǎn shàng kè", "We have class at nine", "Education", 35),
    _c("题", "tí", 2, "topic; question; problem; title", "这个问题很难", "zhège wèntí hěn nán", "This question is very difficult", "Education", 35),
    _c("级", "jí", 2, "level; grade; rank; class", "你上几年级", "nǐ shàng jǐ niánjí", "What grade are you in?", "Education", 35),
    _c("文", "wén", 2, "language; culture; writing", "我在学中文", "wǒ zài xué Zhōngwén", "I'm studying Chinese", "Education", 35),
    _c("字", "zì", 4, "character; word; letter", "我会写汉字", "wǒ huì xiě Hànzì", "I can write Chinese characters", "Education", 35),
    _c("语", "yǔ", 3, "language; speech; words", "她的英语很好", "tā de Yīngyǔ hěn hǎo", "Her English is very good", "Education", 35),
    _c("本", "běn", 3, "root; this; book (measure word)", "我买了一本书", "wǒ mǎi le yī běn shū", "I bought a book", "Education", 35),
    _c("笔", "bǐ", 3, "pen; writing tool", "请给我一支铅笔", "qǐng gěi wǒ yī zhī qiānbǐ", "Please give me a pencil", "Education", 35),
    _c("纸", "zhǐ", 3, "paper", "请给我一张纸", "qǐng gěi wǒ yī zhāng zhǐ", "Please give me a sheet of paper", "Education", 35),
    _c("报", "bào", 4, "newspaper; report; to report", "爸爸在看报纸", "bàba zài kàn bàozhǐ", "Dad is reading the newspaper", "Education", 35),
    _c("言", "yán", 2, "speech; words; to say", "语言很重要", "yǔyán hěn zhòngyào", "Language is very important", "Education", 35),
    _c("书", "shū", 1, "book; letter; document", "我喜欢看书", "wǒ xǐhuān kàn shū", "I like reading books", "Education", 35),

    # -- Week 36: Work --
    _c("工", "gōng", 1, "work; labor; craft", "他在工作", "tā zài gōngzuò", "He is working", "Work", 36),
    _c("作", "zuò", 4, "to do; to make; work", "你的工作是什么", "nǐ de gōngzuò shì shénme", "What is your job?", "Work", 36),
    _c("业", "yè", 4, "industry; business; profession", "他去年毕业了", "tā qùnián bìyè le", "He graduated last year", "Work", 36),
    _c("钱", "qián", 2, "money; coin", "这个多少钱", "zhège duōshǎo qián", "How much is this?", "Work", 36),
    _c("块", "kuài", 4, "piece; chunk; yuan (money)", "这个要十块钱", "zhège yào shí kuài qián", "This costs ten yuan", "Work", 36),
    _c("元", "yuán", 2, "yuan (currency); first; primary", "一共二十元", "yīgòng èrshí yuán", "Twenty yuan in total", "Work", 36),
    _c("爱", "ài", 4, "to love; love; affection", "我爱你", "wǒ ài nǐ", "I love you", "Emotions", 36),
    _c("恨", "hèn", 4, "to hate; hatred; regret", "我很恨这种天气", "wǒ hěn hèn zhè zhǒng tiānqì", "I really hate this kind of weather", "Emotions", 36),
    _c("笑", "xiào", 4, "to laugh; to smile", "笑一笑", "xiào yi xiào", "Smile a little!", "Emotions", 36),
    _c("哭", "kū", 1, "to cry; to weep", "别哭了", "bié kū le", "Stop crying", "Emotions", 36),
    _c("怕", "pà", 4, "to fear; afraid; perhaps", "我怕蛇", "wǒ pà shé", "I'm afraid of snakes", "Emotions", 36),
    _c("急", "jí", 2, "urgent; anxious; impatient", "你别急，慢慢来", "nǐ bié jí, mànmàn lái", "Don't worry, take your time", "Emotions", 36),

    # -- Week 37: Emotions --
    _c("欢", "huān", 1, "happy; joyful (喜欢=to like)", "我很喜欢这里", "wǒ hěn xǐhuān zhèlǐ", "I really like it here", "Emotions", 37),
    _c("喜", "xǐ", 3, "happy; to like; joy (喜欢)", "我喜欢你", "wǒ xǐhuān nǐ", "I like you", "Emotions", 37),
    _c("兴", "xìng", 4, "interest; excited (高兴=happy)", "我很高兴认识你", "wǒ hěn gāoxìng rènshi nǐ", "I'm glad to meet you", "Emotions", 37),
    _c("乐", "lè", 4, "happy; joyful; music (yuè)", "祝你生日快乐", "zhù nǐ shēngrì kuàilè", "Happy birthday to you", "Emotions", 37),
    _c("望", "wàng", 4, "to hope; to gaze; hope", "我希望明天不下雨", "wǒ xīwàng míngtiān bù xiàyǔ", "I hope it doesn't rain tomorrow", "Emotions", 37),
    _c("希", "xī", 1, "hope; to hope (希望)", "希望你好", "xīwàng nǐ hǎo", "Hope you're well", "Emotions", 37),
    _c("感", "gǎn", 3, "to feel; to sense; grateful", "我感觉有点冷", "wǒ gǎnjué yǒudiǎn lěng", "I feel a little cold", "Emotions", 37),
    _c("情", "qíng", 2, "feeling; emotion; situation", "感情很重要", "gǎnqíng hěn zhòngyào", "Feelings are very important", "Emotions", 37),
    _c("担", "dān", 1, "to carry; to worry (担心)", "妈妈很担心我", "māma hěn dānxīn wǒ", "Mom is very worried about me", "Emotions", 37),
    _c("谢", "xiè", 4, "to thank; thanks; to decline", "谢谢你的帮助", "xièxie nǐ de bāngzhù", "Thank you for your help", "Emotions", 37),
    _c("错", "cuò", 4, "wrong; mistake; error", "你说得没错", "nǐ shuō de méi cuò", "What you said is right", "Emotions", 37),
    _c("关", "guān", 1, "to close; to turn off; to concern", "他很关心我", "tā hěn guānxīn wǒ", "He cares about me a lot", "Emotions", 37),

    # -- Week 38: Verbs --
    _c("见", "jiàn", 4, "to see; to meet; to appear", "很高兴见到你", "hěn gāoxìng jiàn dào nǐ", "Nice to meet you", "Verbs", 38),
    _c("系", "xì", 4, "system; department; to tie", "没关系", "méi guānxì", "It doesn't matter", "Verbs", 38),
    _c("完", "wán", 2, "to finish; complete; whole", "我做完了作业", "wǒ zuò wán le zuòyè", "I finished my homework", "Verbs", 38),
    _c("成", "chéng", 2, "to become; to succeed; OK", "他成功了", "tā chénggōng le", "He succeeded", "Verbs", 38),
    _c("变", "biàn", 4, "to change; to become; to vary", "天气变冷了", "tiānqì biàn lěng le", "The weather has gotten cold", "Verbs", 38),
    _c("需", "xū", 1, "to need; must; requirement", "我需要你的帮助", "wǒ xūyào nǐ de bāngzhù", "I need your help", "Verbs", 38),
    _c("准", "zhǔn", 3, "accurate; to allow; standard", "我在准备考试", "wǒ zài zhǔnbèi kǎoshì", "I am preparing for the exam", "Verbs", 38),
    _c("备", "bèi", 4, "to prepare; equipment; ready", "我们准备好了", "wǒmen zhǔnbèi hǎo le", "We are ready", "Verbs", 38),
    _c("参", "cān", 1, "to participate; to join (参加)", "我想参加比赛", "wǒ xiǎng cānjiā bǐsài", "I want to join the competition", "Verbs", 38),
    _c("加", "jiā", 1, "to add; to join; plus", "你要参加活动吗", "nǐ yào cānjiā huódòng ma", "Do you want to join the activity?", "Verbs", 38),
    _c("入", "rù", 4, "to enter; to join; into", "请进入教室", "qǐng jìnrù jiàoshì", "Please enter the classroom", "Verbs", 38),
    _c("帮", "bāng", 1, "to help; to assist", "你能帮忙吗", "nǐ néng bāngmáng ma", "Can you help?", "Verbs", 38),

    # -- Week 39: Daily Verbs --
    _c("睡", "shuì", 4, "to sleep", "我每天十点睡觉", "wǒ měitiān shí diǎn shuìjiào", "I go to sleep at ten every day", "Daily Verbs", 39),
    _c("起", "qǐ", 3, "to rise; to get up; to start", "我早上六点起床", "wǒ zǎoshang liù diǎn qǐchuáng", "I get up at six in the morning", "Daily Verbs", 39),
    _c("等", "děng", 3, "to wait; rank; class; etc.", "等一下", "děng yīxià", "Wait a moment", "Daily Verbs", 39),
    _c("唱", "chàng", 4, "to sing", "她喜欢唱歌", "tā xǐhuān chàng gē", "She likes to sing", "Daily Verbs", 39),
    _c("跳", "tiào", 4, "to jump; to dance; to skip", "我们一起跳舞吧", "wǒmen yīqǐ tiào wǔ ba", "Let us dance together", "Daily Verbs", 39),
    _c("玩", "wán", 2, "to play; to have fun; to visit", "孩子们在玩游戏", "háizimen zài wán yóuxì", "The children are playing games", "Daily Verbs", 39),
    _c("画", "huà", 4, "to draw; painting; picture", "妹妹喜欢画画", "mèimei xǐhuān huà huà", "My younger sister likes to draw", "Daily Verbs", 39),
    _c("骑", "qí", 2, "to ride (horse/bike)", "他每天骑自行车上班", "tā měitiān qí zìxíngchē shàngbān", "He rides a bike to work every day", "Daily Verbs", 39),
    _c("踢", "tī", 1, "to kick; to play (soccer)", "我们下午踢足球", "wǒmen xiàwǔ tī zúqiú", "We play soccer in the afternoon", "Daily Verbs", 39),
    _c("拍", "pāi", 1, "to clap; to film; to hit", "我想拍照", "wǒ xiǎng pāi zhào", "I want to take a photo", "Daily Verbs", 39),
    _c("搞", "gǎo", 3, "to do; to make; to handle", "这件事我搞定了", "zhè jiàn shì wǒ gǎo dìng le", "I got this thing done", "Daily Verbs", 39),
    _c("像", "xiàng", 4, "to resemble; like; image", "他好像生病了", "tā hǎoxiàng shēngbìng le", "He seems to be sick", "Daily Verbs", 39),

    # -- Week 40: Technology --
    _c("电", "diàn", 4, "electricity; electric", "我的电脑很快", "wǒ de diànnǎo hěn kuài", "My computer is very fast", "Technology", 40),
    _c("话", "huà", 4, "speech; words; conversation", "我给妈妈打电话", "wǒ gěi māma dǎ diànhuà", "I call my mom", "Technology", 40),
    _c("机", "jī", 1, "machine; opportunity; airplane", "我的手机没电了", "wǒ de shǒujī méi diàn le", "My phone is out of battery", "Technology", 40),
    _c("网", "wǎng", 3, "net; internet; network", "我在家上网", "wǒ zài jiā shàng wǎng", "I go online at home", "Technology", 40),
    _c("脑", "nǎo", 3, "brain; mind (电脑=computer)", "这台电脑是新的", "zhè tái diànnǎo shì xīn de", "This computer is new", "Technology", 40),
    _c("视", "shì", 4, "to look; vision (电视=TV)", "爸爸在看电视", "bàba zài kàn diànshì", "Dad is watching TV", "Technology", 40),
    _c("影", "yǐng", 3, "shadow; movie; image", "我们去看电影吧", "wǒmen qù kàn diànyǐng ba", "Let us go watch a movie", "Technology", 40),
    _c("信", "xìn", 4, "letter; to believe; trust; faith", "我相信你", "wǒ xiāngxìn nǐ", "I believe you", "Technology", 40),
    _c("照", "zhào", 4, "to shine; photo; according to", "这张照片很好看", "zhè zhāng zhàopiàn hěn hǎokàn", "This photo looks great", "Technology", 40),
    _c("片", "piàn", 4, "slice; piece; film; (照片=photo)", "请给我看照片", "qǐng gěi wǒ kàn zhàopiàn", "Please show me the photo", "Technology", 40),
    _c("号", "hào", 4, "number; date; mark; size", "你的电话号码是多少", "nǐ de diànhuà hàomǎ shì duōshao", "What is your phone number?", "Technology", 40),
    _c("音", "yīn", 1, "sound; voice; tone; music", "我喜欢听音乐", "wǒ xǐhuān tīng yīnyuè", "I like listening to music", "Technology", 40),

    # -- Week 41: Objects --
    _c("色", "sè", 4, "color; look; type", "你喜欢什么颜色", "nǐ xǐhuān shénme yánsè", "What color do you like?", "Objects", 41),
    _c("件", "jiàn", 4, "item; piece (measure word)", "我有一件事要说", "wǒ yǒu yī jiàn shì yào shuō", "I have one thing to say", "Objects", 41),
    _c("条", "tiáo", 2, "strip; (measure for long things)", "前面有一条路", "qiánmiàn yǒu yī tiáo lù", "There is a road ahead", "Objects", 41),
    _c("张", "zhāng", 1, "measure for flat things; to open", "桌子上有一张纸", "zhuōzi shàng yǒu yī zhāng zhǐ", "There is a sheet of paper on the table", "Objects", 41),
    _c("双", "shuāng", 1, "pair; double; both; even (number)", "我买了一双鞋", "wǒ mǎi le yī shuāng xié", "I bought a pair of shoes", "Objects", 41),
    _c("辆", "liàng", 4, "measure word for vehicles", "他有一辆车", "tā yǒu yī liàng chē", "He has a car", "Objects", 41),
    _c("化", "huà", 4, "change; -ize; culture (文化)", "中国文化很有意思", "Zhōngguó wénhuà hěn yǒu yìsi", "Chinese culture is very interesting", "Society", 41),
    _c("民", "mín", 2, "people; citizen; folk", "人民很重要", "rénmín hěn zhòngyào", "The people are very important", "Society", 41),
    _c("法", "fǎ", 3, "law; method; way; France", "这个方法很好", "zhège fāngfǎ hěn hǎo", "This method is very good", "Society", 41),
    _c("历", "lì", 4, "history; experience; calendar", "我喜欢学历史", "wǒ xǐhuān xué lìshǐ", "I like studying history", "Society", 41),
    _c("史", "shǐ", 3, "history; annals", "中国历史很长", "Zhōngguó lìshǐ hěn cháng", "Chinese history is very long", "Society", 41),

    # -- Week 42: Society --
    _c("汉", "hàn", 4, "Han Chinese; man; Chinese", "我在学汉语", "wǒ zài xué Hànyǔ", "I am studying Chinese", "Society", 42),
    _c("介", "jiè", 4, "to introduce; between", "请你介绍一下", "qǐng nǐ jièshào yīxià", "Please introduce yourself", "Society", 42),
    _c("绍", "shào", 4, "to introduce; to continue", "我来做个自我介绍", "wǒ lái zuò ge zìwǒ jièshào", "Let me give a self-introduction", "Society", 42),
    _c("迎", "yíng", 2, "to welcome; to meet; to face", "欢迎光临", "huānyíng guānglín", "Welcome!", "Society", 42),
    _c("共", "gòng", 4, "common; shared; altogether", "一共多少钱", "yīgòng duōshao qián", "How much is it altogether?", "Society", 42),
    _c("提", "tí", 2, "to raise; to mention; to carry", "你可以提问", "nǐ kěyǐ tíwèn", "You may ask a question", "Society", 42),
    _c("管", "guǎn", 3, "to manage; tube; pipe; regardless", "不管怎样我都去", "bùguǎn zěnyàng wǒ dōu qù", "No matter what, I will go", "Society", 42),
    _c("事", "shì", 4, "matter; thing; affair; event", "你有什么事吗", "nǐ yǒu shénme shì ma", "Is there something you need?", "Society", 42),
    _c("理", "lǐ", 3, "reason; logic; to manage; physics", "你说的有道理", "nǐ shuō de yǒu dàolǐ", "What you said makes sense", "Society", 42),
    _c("力", "lì", 4, "power; strength; force; ability", "他学习很努力", "tā xuéxí hěn nǔlì", "He studies very hard", "Society", 42),
    _c("主", "zhǔ", 3, "main; master; owner; host", "这是主要的原因", "zhè shì zhǔyào de yuányīn", "This is the main reason", "Society", 42),

    # -- Week 43: Abstract --
    _c("定", "dìng", 4, "to fix; to decide; certain", "你一定要来", "nǐ yīdìng yào lái", "You must come", "Abstract", 43),
    _c("种", "zhǒng", 3, "kind; type; seed; to plant", "这种水果很好吃", "zhè zhǒng shuǐguǒ hěn hǎochī", "This kind of fruit is delicious", "Abstract", 43),
    _c("样", "yàng", 4, "shape; type; way; (怎么样=how)", "我们的想法一样", "wǒmen de xiǎngfǎ yīyàng", "Our ideas are the same", "Abstract", 43),
    _c("然", "rán", 2, "so; like that; (当然=of course)", "你当然可以来", "nǐ dāngrán kěyǐ lái", "Of course you can come", "Abstract", 43),
    _c("当", "dāng", 1, "to be; to serve as; when; should", "他当然会来", "tā dāngrán huì lái", "He will of course come", "Abstract", 43),
    _c("因", "yīn", 1, "because; reason; cause", "因为下雨我没去", "yīnwèi xià yǔ wǒ méi qù", "I did not go because it rained", "Abstract", 43),
    _c("虽", "suī", 1, "although; even though (虽然)", "虽然很难但我会试", "suīrán hěn nán dàn wǒ huì shì", "Although it is hard, I will try", "Abstract", 43),
    _c("但", "dàn", 4, "but; however; only", "很贵但是很好", "hěn guì dànshì hěn hǎo", "It is expensive but very good", "Abstract", 43),
    _c("如", "rú", 2, "as if; like; if; such as", "如果明天下雨就不去", "rúguǒ míngtiān xià yǔ jiù bú qù", "If it rains tomorrow, we will not go", "Abstract", 43),
    _c("正", "zhèng", 4, "just; right; correct; straight", "我正在吃饭", "wǒ zhèngzài chīfàn", "I am eating right now", "Abstract", 43),
    _c("真", "zhēn", 1, "real; true; genuine; really", "真的吗", "zhēn de ma", "Really?", "Abstract", 43),

    # -- Week 44: Function Words --
    _c("只", "zhǐ", 3, "only; just; merely", "我只有一个哥哥", "wǒ zhǐyǒu yī ge gēge", "I only have one older brother", "Function Words", 44),
    _c("别", "bié", 2, "don't; other; to leave", "请你别担心", "qǐng nǐ bié dānxīn", "Please don't worry", "Function Words", 44),
    _c("另", "lìng", 4, "other; another; separate", "另外还有一个问题", "lìngwài hái yǒu yī ge wèntí", "In addition, there is another question", "Function Words", 44),
    _c("自", "zì", 4, "self; from; since; naturally", "要相信自己", "yào xiāngxìn zìjǐ", "You should believe in yourself", "Function Words", 44),
    _c("己", "jǐ", 3, "self; oneself (自己)", "这是我自己做的", "zhè shì wǒ zìjǐ zuò de", "I made this myself", "Function Words", 44),
    _c("特", "tè", 4, "special; particular; especially", "今天特别冷", "jīntiān tèbié lěng", "It is especially cold today", "Function Words", 44),
    _c("且", "qiě", 3, "and; moreover; for the time being", "他聪明而且努力", "tā cōngmíng érqiě nǔlì", "He is smart and also hardworking", "Function Words", 44),
    _c("除", "chú", 2, "to remove; except; besides; to divide", "除了他都来了", "chúle tā dōu lái le", "Everyone came except him", "Function Words", 44),
    _c("根", "gēn", 1, "root; basis; (根据=according to)", "根据天气预报明天有雨", "gēnjù tiānqì yùbào míngtiān yǒu yǔ", "According to the forecast, it will rain tomorrow", "Function Words", 44),
    _c("据", "jù", 4, "according to; evidence; to occupy", "根据老师说的去做", "gēnjù lǎoshī shuō de qù zuò", "Do it according to what the teacher said", "Function Words", 44),

    # -- Week 45: Sequence --
    _c("终", "zhōng", 1, "end; final; eventually", "他最终成功了", "tā zuìzhōng chénggōng le", "He finally succeeded", "Sequence", 45),
    _c("总", "zǒng", 3, "always; overall; general; total", "他总是迟到", "tā zǒngshì chídào", "He is always late", "Sequence", 45),

    # -- Week 46: Geography --
    _c("省", "shěng", 3, "province; to save; to omit", "我们要省钱", "wǒmen yào shěng qián", "We need to save money", "Geography", 46),
    _c("镇", "zhèn", 4, "town; to calm; to suppress", "我住在一个小镇", "wǒ zhù zài yī ge xiǎo zhèn", "I live in a small town", "Geography", 46),
    _c("农", "nóng", 2, "agriculture; farming; farmer", "他来自农村", "tā láizì nóngcūn", "He comes from the countryside", "Geography", 46),
    _c("平", "píng", 2, "flat; level; peaceful; ordinary", "祝你一路平安", "zhù nǐ yī lù píng'ān", "Wishing you a safe journey", "Geography", 46),
    _c("次", "cì", 4, "time (occurrence); order; next", "下次我请你吃饭", "xià cì wǒ qǐng nǐ chīfàn", "Next time I will treat you to a meal", "HSK Vocab", 46),
    _c("第", "dì", 4, "ordinal prefix (第一=first)", "这是我第一次来中国", "zhè shì wǒ dì yī cì lái Zhōngguó", "This is my first time coming to China", "HSK Vocab", 46),
    _c("段", "duàn", 4, "section; paragraph; period", "我等了一段时间", "wǒ děng le yī duàn shíjiān", "I waited for a period of time", "HSK Vocab", 46),
    _c("篇", "piān", 1, "measure for articles/essays", "他写了一篇文章", "tā xiě le yī piān wénzhāng", "He wrote an article", "HSK Vocab", 46),

    # -- Week 47: Animals --
    _c("猫", "māo", 1, "cat", "我家有一只小猫", "wǒ jiā yǒu yī zhī xiǎo māo", "My family has a kitten", "Animals", 47),
    _c("狗", "gǒu", 3, "dog", "那只小狗很可爱", "nà zhī xiǎo gǒu hěn kě'ài", "That puppy is very cute", "Animals", 47),
    _c("鱼", "yú", 2, "fish", "我喜欢吃鱼", "wǒ xǐhuan chī yú", "I like to eat fish", "Animals", 47),
    _c("马", "mǎ", 3, "horse; (马上=immediately)", "他马上就来", "tā mǎshàng jiù lái", "He is coming right away", "Animals", 47),
    _c("虫", "chóng", 2, "insect; bug; worm", "我怕虫子", "wǒ pà chóngzi", "I am afraid of bugs", "Animals", 47),
    _c("象", "xiàng", 4, "elephant; image; shape", "大象很大", "dà xiàng hěn dà", "Elephants are very big", "Animals", 47),
    _c("借", "jiè", 4, "to borrow; to lend", "我想借一本书", "wǒ xiǎng jiè yī běn shū", "I want to borrow a book", "Verbs", 47),
    _c("相", "xiāng", 1, "mutually; each other; to look at", "我相信你", "wǒ xiāngxìn nǐ", "I believe you", "Verbs", 47),
    _c("护", "hù", 4, "to protect; to guard", "你的护照在哪儿", "nǐ de hùzhào zài nǎr", "Where is your passport?", "Verbs", 47),
    _c("检", "jiǎn", 3, "to check; to examine; to inspect", "医生在检查病人", "yīshēng zài jiǎnchá bìngrén", "The doctor is examining the patient", "Verbs", 47),
    _c("查", "chá", 2, "to check; to look up; to inspect", "我去医院检查身体", "wǒ qù yīyuàn jiǎnchá shēntǐ", "I am going to the hospital for a checkup", "Verbs", 47),

    # -- Week 48: Verbs --
    _c("死", "sǐ", 3, "to die; death; extremely (slang)", "我今天累死了", "wǒ jīntiān lèi sǐ le", "I am dead tired today", "Verbs", 48),
    _c("活", "huó", 2, "to live; alive; lively; work", "他的生活很快乐", "tā de shēnghuó hěn kuàilè", "His life is very happy", "Verbs", 48),
    _c("掉", "diào", 4, "to fall; to drop; to lose", "我的手机掉了", "wǒ de shǒujī diào le", "My phone dropped", "Verbs", 48),
    _c("算", "suàn", 4, "to count; to calculate; to plan", "你打算去哪儿", "nǐ dǎsuàn qù nǎr", "Where do you plan to go?", "Verbs", 48),
    _c("刷", "shuā", 1, "to brush; to swipe", "我每天早上刷牙", "wǒ měitiān zǎoshang shuā yá", "I brush my teeth every morning", "Verbs", 48),
    _c("练", "liàn", 4, "to practice; to train; exercise", "我每天练习写字", "wǒ měitiān liànxí xiě zì", "I practice writing characters every day", "Verbs", 48),
    _c("懒", "lǎn", 3, "lazy", "他太懒了，不想起床", "tā tài lǎn le, bù xiǎng qǐchuáng", "He is too lazy and does not want to get up", "Verbs", 48),
    _c("够", "gòu", 4, "enough; sufficient; quite", "够了，别说了", "gòu le, bié shuō le", "Enough, stop talking!", "Verbs", 48),
    _c("容", "róng", 2, "to contain; to tolerate; face", "这个问题很容易", "zhège wèntí hěn róngyì", "This question is very easy", "Verbs", 48),
    _c("差", "chà", 4, "to differ; poor; lacking; almost", "我们的想法差不多", "wǒmen de xiǎngfǎ chà bu duō", "Our ideas are about the same", "Verbs", 48),
    _c("表", "biǎo", 3, "surface; to express; watch; form", "他表示同意", "tā biǎoshì tóngyì", "He expressed agreement", "Verbs", 48),
    _c("示", "shì", 4, "to show; to indicate; to reveal", "她表示感谢", "tā biǎoshì gǎnxiè", "She expressed her thanks", "Verbs", 48),

    # -- Week 49: HSK Vocab --
    _c("星", "xīng", 1, "star; satellite; (星期=week)", "星期天我不上班", "xīngqītiān wǒ bù shàngbān", "I do not work on Sunday", "HSK Vocab", 49),
    _c("漂", "piào", 4, "pretty (漂亮); to float (piāo)", "她穿的裙子很漂亮", "tā chuān de qúnzi hěn piàoliang", "The dress she is wearing is very pretty", "HSK Vocab", 49),
    _c("便", "pián", 2, "cheap (便宜); convenient (biàn)", "这个东西很便宜", "zhège dōngxi hěn piányi", "This thing is very cheap", "HSK Vocab", 49),
    _c("宜", "yí", 2, "suitable; appropriate (便宜=cheap)", "那家店的水果便宜", "nà jiā diàn de shuǐguǒ piányi", "The fruit at that store is cheap", "HSK Vocab", 49),
    _c("舒", "shū", 1, "comfortable; to stretch (舒服)", "这把椅子很舒服", "zhè bǎ yǐzi hěn shūfu", "This chair is very comfortable", "HSK Vocab", 49),
    _c("应", "yīng", 1, "should; ought to; to respond", "你应该多休息", "nǐ yīnggāi duō xiūxi", "You should rest more", "HSK Vocab", 49),
    _c("该", "gāi", 1, "should; ought to; that", "我们应该走了", "wǒmen yīnggāi zǒu le", "We should go now", "HSK Vocab", 49),
    _c("往", "wǎng", 3, "toward; to go; past; previous", "请往前走", "qǐng wǎng qián zǒu", "Please go forward", "HSK Vocab", 49),
    _c("跟", "gēn", 1, "with; to follow; and", "跟我来", "gēn wǒ lái", "Follow me", "HSK Vocab", 49),
    _c("猪", "zhū", 1, "pig; pork", "我不吃猪肉", "wǒ bù chī zhūròu", "I do not eat pork", "HSK Vocab", 49),
    _c("鲜", "xiān", 1, "fresh; delicious; bright", "这些菜很新鲜", "zhèxiē cài hěn xīnxiān", "These vegetables are very fresh", "HSK Vocab", 49),
    _c("香", "xiāng", 1, "fragrant; delicious; popular", "我喜欢吃香蕉", "wǒ xǐhuan chī xiāngjiāo", "I like to eat bananas", "HSK Vocab", 49),

    # -- Week 50: HSK Vocab --
    _c("甜", "tián", 2, "sweet", "这个蛋糕很甜", "zhège dàngāo hěn tián", "This cake is very sweet", "HSK Vocab", 50),
    _c("咸", "xián", 2, "salty", "这个菜太咸了", "zhège cài tài xián le", "This dish is too salty", "HSK Vocab", 50),
    _c("辣", "là", 4, "spicy; hot (taste)", "这个菜太辣了", "zhège cài tài là le", "This dish is too spicy!", "HSK Vocab", 50),
    _c("健", "jiàn", 4, "healthy; strong (健康)", "运动对健康有好处", "yùndòng duì jiànkāng yǒu hǎochù", "Exercise is good for health", "HSK Vocab", 50),
    _c("康", "kāng", 1, "healthy; well-being (健康)", "祝你身体健康", "zhù nǐ shēntǐ jiànkāng", "Wishing you good health", "HSK Vocab", 50),
    _c("闲", "xián", 2, "idle; free time; leisure", "我今天有空闲", "wǒ jīntiān yǒu kòngxián", "I have free time today", "HSK Vocab", 50),
    _c("牙", "yá", 2, "tooth", "你刷牙了吗", "nǐ shuā yá le ma", "Did you brush your teeth?", "HSK Vocab", 50),
    _c("脸", "liǎn", 3, "face", "她每天早上洗脸", "tā měitiān zǎoshang xǐ liǎn", "She washes her face every morning", "HSK Vocab", 50),
    _c("声", "shēng", 1, "sound; voice; tone", "我听到一个声音", "wǒ tīngdào yī gè shēngyīn", "I heard a sound", "HSK Vocab", 50),
    _c("目", "mù", 4, "eye; item; list (节目=program)", "这个节目很好看", "zhège jiémù hěn hǎokàn", "This show is very good", "HSK Vocab", 50),
    _c("休", "xiū", 1, "to rest; to cease (休息)", "我想休息一会儿", "wǒ xiǎng xiūxi yīhuìr", "I want to rest for a while", "HSK Vocab", 50),
    _c("息", "xī", 1, "to rest; breath; news; interest", "请休息一下吧", "qǐng xiūxi yīxià ba", "Please take a rest", "HSK Vocab", 50),

    # -- Week 51: HSK Vocab --
    _c("越", "yuè", 4, "to cross; more and more (越来越)", "他的中文越来越好", "tā de Zhōngwén yuè lái yuè hǎo", "His Chinese is getting better and better", "HSK Vocab", 51),
    _c("极", "jí", 2, "extremely; pole; utmost", "今天的天气好极了", "jīntiān de tiānqì hǎo jí le", "The weather today is wonderful!", "HSK Vocab", 51),
    _c("刚", "gāng", 1, "just now; just; barely", "他刚才给我打电话了", "tā gāngcái gěi wǒ dǎ diànhuà le", "He just called me a moment ago", "HSK Vocab", 51),
    _c("附", "fù", 4, "nearby; to attach (附近=nearby)", "附近有一家超市", "fùjìn yǒu yī jiā chāoshì", "There is a supermarket nearby", "HSK Vocab", 51),
    _c("喂", "wèi", 4, "hello (on phone); hey; to feed", "喂，你好，请问你找谁", "wèi, nǐ hǎo, qǐngwèn nǐ zhǎo shéi", "Hello, may I ask who you are looking for?", "HSK Vocab", 51),
    _c("数", "shù", 4, "number; to count (shǔ)", "我喜欢学数学", "wǒ xǐhuan xué shùxué", "I like studying mathematics", "HSK Vocab", 51),
    _c("冰", "bīng", 1, "ice; cold; to freeze", "我想喝冰水", "wǒ xiǎng hē bīng shuǐ", "I want to drink ice water", "HSK Vocab", 51),
    _c("聪", "cōng", 1, "clever; smart (聪明)", "这个孩子很聪明", "zhège háizi hěn cōngming", "This child is very smart", "HSK Vocab", 51),
    _c("奇", "qí", 2, "strange; odd; wonderful", "这件事很奇怪", "zhè jiàn shì hěn qíguài", "This matter is very strange", "HSK Vocab", 51),
    _c("怪", "guài", 4, "strange; to blame; monster", "真奇怪，他怎么没来", "zhēn qíguài, tā zěnme méi lái", "How strange, why did he not come?", "HSK Vocab", 51),
    _c("突", "tū", 1, "suddenly; to protrude (突然)", "他突然走了", "tā tūrán zǒu le", "He suddenly left", "HSK Vocab", 51),
    _c("危", "wēi", 1, "danger; to endanger (危险)", "那个地方很危险", "nàge dìfang hěn wēixiǎn", "That place is very dangerous", "HSK Vocab", 51),

    # -- Week 52: HSK Vocab --
    _c("险", "xiǎn", 3, "danger; risk; insurance", "开车太快很危险", "kāichē tài kuài hěn wēixiǎn", "Driving too fast is very dangerous", "HSK Vocab", 52),
    _c("努", "nǔ", 3, "to strive; effort (努力)", "他每天努力学习", "tā měitiān nǔlì xuéxí", "He studies hard every day", "HSK Vocab", 52),
    _c("必", "bì", 4, "must; certainly; necessary", "你必须完成作业", "nǐ bìxū wánchéng zuòyè", "You must finish your homework", "HSK Vocab", 52),
    _c("须", "xū", 1, "must; beard; to need (必须)", "我们必须去学校", "wǒmen bìxū qù xuéxiào", "We must go to school", "HSK Vocab", 52),
    _c("季", "jì", 4, "season; quarter (of year)", "一年有四季", "yī nián yǒu sì jì", "A year has four seasons", "HSK Vocab", 52),
    _c("忽", "hū", 1, "suddenly; to neglect (忽然)", "天忽然下雨了", "tiān hūrán xià yǔ le", "It suddenly started to rain", "HSK Vocab", 52),
    _c("味", "wèi", 4, "taste; flavor; smell", "这个菜的味道很好", "zhège cài de wèidào hěn hǎo", "This dish tastes very good", "HSK Vocab", 52),
    _c("饱", "bǎo", 3, "full (after eating); satisfied", "我吃饱了", "wǒ chī bǎo le", "I am full", "HSK Vocab", 52),
    _c("份", "fèn", 4, "portion; share; copy", "我要一份米饭", "wǒ yào yī fèn mǐfàn", "I want a serving of rice", "HSK Vocab", 52),
    _c("戴", "dài", 4, "to wear (hat/glasses/watch)", "今天很冷，你戴帽子吧", "jīntiān hěn lěng, nǐ dài màozi ba", "It is cold today, you should wear a hat", "HSK Vocab", 52),
    _c("讲", "jiǎng", 3, "to speak; to tell; to explain", "妈妈给我讲故事", "māma gěi wǒ jiǎng gùshi", "Mom tells me stories", "HSK Vocab", 52),

    # -- Week 53: HSK Vocab --
    _c("故", "gù", 4, "old; reason; 故事=story", "我喜欢听故事", "wǒ xǐhuan tīng gùshi", "I like listening to stories", "HSK Vocab", 53),
    _c("响", "xiǎng", 3, "to ring; to sound; loud; influence", "这件事影响很大", "zhè jiàn shì yǐngxiǎng hěn dà", "This matter has a big influence", "HSK Vocab", 53),
    _c("解", "jiě", 3, "to understand; to solve; to untie", "我想了解中国文化", "wǒ xiǎng liǎojiě Zhōngguó wénhuà", "I want to understand Chinese culture", "HSK Vocab", 53),
    _c("按", "àn", 4, "to press; to push; according to", "请你按时来上课", "qǐng nǐ ànshí lái shàngkè", "Please come to class on time", "HSK Vocab", 53),
    _c("普", "pǔ", 3, "universal; general (普通)", "他会说普通话", "tā huì shuō pǔtōnghuà", "He can speak Mandarin", "HSK Vocab", 53),
    _c("通", "tōng", 1, "through; to communicate; common", "这里的交通很方便", "zhèlǐ de jiāotōng hěn fāngbiàn", "The transportation here is very convenient", "HSK Vocab", 53),
    _c("遇", "yù", 4, "to meet; to encounter", "我在路上遇到了老师", "wǒ zài lùshang yùdào le lǎoshī", "I ran into my teacher on the road", "HSK Vocab", 53),
    _c("复", "fù", 4, "to repeat; to review; again; complex", "考试前我要复习", "kǎoshì qián wǒ yào fùxí", "I need to review before the exam", "HSK Vocab", 53),

    # -- Week 54: HSK Vocab --
    _c("留", "liú", 2, "to stay; to keep; to leave behind", "她想去美国留学", "tā xiǎng qù Měiguó liúxué", "She wants to study abroad in America", "HSK Vocab", 54),
    _c("程", "chéng", 2, "journey; process; procedure", "学习是一个过程", "xuéxí shì yī gè guòchéng", "Learning is a process", "HSK Vocab", 54),
    _c("愿", "yuàn", 4, "to wish; to want; willing", "我愿意帮助你", "wǒ yuànyì bāngzhù nǐ", "I am willing to help you", "HSK Vocab", 54),
    _c("秒", "miǎo", 3, "second (unit of time)", "请等我几秒钟", "qǐng děng wǒ jǐ miǎo zhōng", "Please wait a few seconds for me", "HSK Vocab", 54),
    _c("温", "wēn", 1, "warm; temperature; to review", "今天的温度很高", "jīntiān de wēndù hěn gāo", "The temperature is very high today", "HSK Vocab", 54),
    _c("饮", "yǐn", 3, "to drink; beverage (饮料)", "你想喝什么饮料", "nǐ xiǎng hē shénme yǐnliào", "What beverage would you like to drink?", "HSK Vocab", 54),
    _c("料", "liào", 4, "material; to expect; feed", "冰箱里有饮料", "bīngxiāng lǐ yǒu yǐnliào", "There are beverages in the fridge", "HSK Vocab", 54),
    _c("汽", "qì", 4, "steam; gas; vapor (汽车=car)", "他开汽车去上班", "tā kāi qìchē qù shàngbān", "He drives a car to work", "HSK Vocab", 54),
]

# Total: 600 characters
assert len(CHARACTERS) == 600, f"Expected 600 characters, got {len(CHARACTERS)}"
