# HSK 1-3 Chinese Characters (600 characters)
# Organized into themed weekly groups for daily SMS lessons
# 3 characters/day x 6 days/week = 18 new chars/week
# Full cycle: ~33 weeks to cover all characters

def _c(ch, py, t, mn, ecn, epy, een, gr, wk):
    return {"char": ch, "pinyin": py, "tone": t, "meaning": mn,
            "example_cn": ecn, "example_pinyin": epy, "example_en": een,
            "group": gr, "week": wk}

CHARACTERS = [

    # -- Week 1: Core Grammar --
    _c("的", "de", 5, "possessive particle ('s); descriptive marker", "我的书", "wǒ de shū", "my book", "Core Grammar", 1),
    _c("是", "shì", 4, "to be (am/is/are)", "我是学生", "wǒ shì xuésheng", "I am a student", "Core Grammar", 1),
    _c("不", "bù", 4, "not; no (general negation)", "我不累", "wǒ bù lèi", "I am not tired", "Core Grammar", 1),
    _c("了", "le", 5, "completed action; change of state", "他来了", "tā lái le", "He came / He's here", "Core Grammar", 1),
    _c("在", "zài", 4, "at; in; on; to be at a place", "她在家", "tā zài jiā", "She is at home", "Core Grammar", 1),
    _c("有", "yǒu", 3, "to have; there is/are", "我有朋友", "wǒ yǒu péngyou", "I have friends", "Core Grammar", 1),
    _c("我", "wǒ", 3, "I; me", "我叫小明", "wǒ jiào Xiǎo Míng", "My name is Xiao Ming", "Pronouns", 1),
    _c("你", "nǐ", 3, "you (singular)", "你好吗", "nǐ hǎo ma", "How are you?", "Pronouns", 1),
    _c("他", "tā", 1, "he; him", "他是老师", "tā shì lǎoshī", "He is a teacher", "Pronouns", 1),
    _c("她", "tā", 1, "she; her", "她很漂亮", "tā hěn piàoliang", "She is very pretty", "Pronouns", 1),
    _c("它", "tā", 1, "it (animals/things)", "它是猫", "tā shì māo", "It is a cat", "Pronouns", 1),
    _c("们", "men", 5, "plural suffix: 我们=we, 他们=they", "我们是朋友", "wǒmen shì péngyou", "We are friends", "Pronouns", 1),

    # -- Week 2: Connectors --
    _c("这", "zhè", 4, "this; these", "这是什么", "zhè shì shénme", "What is this?", "Connectors", 2),
    _c("那", "nà", 4, "that; those; then", "那个人是谁", "nà gè rén shì shuí", "Who is that person?", "Connectors", 2),
    _c("和", "hé", 2, "and; with", "我和你", "wǒ hé nǐ", "you and me", "Connectors", 2),
    _c("也", "yě", 3, "also; too", "我也喜欢", "wǒ yě xǐhuān", "I also like it", "Connectors", 2),
    _c("都", "dōu", 1, "all; both; already", "我们都去", "wǒmen dōu qù", "We all go", "Connectors", 2),
    _c("很", "hěn", 3, "very; quite", "她很高兴", "tā hěn gāoxìng", "She is very happy", "Connectors", 2),
    _c("没", "méi", 2, "not; haven't; without", "没有问题", "méiyǒu wèntí", "No problem", "Modal Verbs", 2),
    _c("就", "jiù", 4, "then; right away; only", "我就来", "wǒ jiù lái", "I'll be right there", "Modal Verbs", 2),
    _c("会", "huì", 4, "can; will; know how to", "你会游泳吗", "nǐ huì yóuyǒng ma", "Can you swim?", "Modal Verbs", 2),
    _c("能", "néng", 2, "can; able to; capable", "你能帮我吗", "nǐ néng bāng wǒ ma", "Can you help me?", "Modal Verbs", 2),
    _c("要", "yào", 4, "to want; need; will; must", "我要喝水", "wǒ yào hē shuǐ", "I want water", "Modal Verbs", 2),
    _c("可", "kě", 3, "can; may; approve", "可以", "kěyǐ", "OK / you may", "Modal Verbs", 2),

    # -- Week 3: Particles --
    _c("吗", "ma", 5, "yes/no question particle", "你好吗", "nǐ hǎo ma", "How are you?", "Particles", 3),
    _c("呢", "ne", 5, "question particle (and you?; what about?)", "你呢", "nǐ ne", "And you? / What about you?", "Particles", 3),
    _c("什", "shén", 2, "what (part of 什么)", "什么时候", "shénme shíhou", "When? (what time)", "Question Words", 3),
    _c("么", "me", 5, "suffix (什么=what, 怎么=how)", "怎么了", "zěnme le", "What happened?", "Question Words", 3),
    _c("吧", "ba", 5, "suggestion particle (let's...)", "走吧", "zǒu ba", "Let's go", "Particles", 3),
    _c("啊", "a", 5, "exclamation; emphasis particle", "好啊", "hǎo a", "Great! / Sure!", "Particles", 3),
    _c("再", "zài", 4, "again; once more; then", "再见", "zàijiàn", "Goodbye (see you again)", "Adverbs", 3),
    _c("还", "hái", 2, "still; yet; also; even more", "还有吗", "hái yǒu ma", "Is there still more?", "Adverbs", 3),
    _c("已", "yǐ", 3, "already (part of 已经)", "已经到了", "yǐjīng dào le", "Already arrived", "Adverbs", 3),
    _c("经", "jīng", 1, "to pass through; already (已经)", "经过", "jīngguò", "to pass by; through", "Adverbs", 3),
    _c("才", "cái", 2, "only then; just now; only", "他才来", "tā cái lái", "He only just arrived", "Adverbs", 3),
    _c("又", "yòu", 4, "again; also; both...and...", "又大又好", "yòu dà yòu hǎo", "Both big and good", "Adverbs", 3),

    # -- Week 4: Adverbs --
    _c("太", "tài", 4, "too; extremely; very", "太好了", "tài hǎo le", "That's great! / Too good!", "Adverbs", 4),
    _c("最", "zuì", 4, "most; -est (superlative)", "最好", "zuì hǎo", "the best", "Adverbs", 4),
    _c("更", "gèng", 4, "more; even more", "更好", "gèng hǎo", "even better", "Adverbs", 4),
    _c("比", "bǐ", 3, "to compare; than", "他比我高", "tā bǐ wǒ gāo", "He is taller than me", "Adverbs", 4),
    _c("非", "fēi", 1, "not; wrong; (非常=very)", "非常好", "fēicháng hǎo", "extremely good", "Adverbs", 4),
    _c("常", "cháng", 2, "often; frequently; normal", "经常", "jīngcháng", "often; frequently", "Adverbs", 4),
    _c("以", "yǐ", 3, "by means of; so as to", "以后", "yǐhòu", "after; in the future", "Function Words", 4),
    _c("从", "cóng", 2, "from; since; follow", "你从哪里来", "nǐ cóng nǎlǐ lái", "Where are you from?", "Function Words", 4),
    _c("于", "yú", 2, "at; in; to (formal)", "关于", "guānyú", "about; regarding", "Function Words", 4),
    _c("为", "wèi", 4, "for; because of; in order to", "为什么", "wèishénme", "Why?", "Function Words", 4),
    _c("被", "bèi", 4, "passive marker (by); quilt", "被批评了", "bèi pīpíng le", "was criticized", "Function Words", 4),
    _c("把", "bǎ", 3, "disposal marker; to take/hold", "把书放下", "bǎ shū fàng xià", "Put the book down", "Function Words", 4),

    # -- Week 5: Function Words --
    _c("给", "gěi", 3, "to give; for; to", "给我看", "gěi wǒ kàn", "Show me / Let me see", "Function Words", 5),
    _c("让", "ràng", 4, "to let; allow; to ask sb to", "让我来", "ràng wǒ lái", "Let me do it", "Function Words", 5),
    _c("向", "xiàng", 4, "toward; facing; direction", "向前走", "xiàng qián zǒu", "Walk forward", "Function Words", 5),
    _c("对", "duì", 4, "correct; toward; pair", "对不起", "duìbuqǐ", "Sorry; I'm sorry", "Function Words", 5),
    _c("着", "zhe", 5, "ongoing action particle (-ing)", "看着我", "kàn zhe wǒ", "Look at me (keep looking)", "Function Words", 5),
    _c("过", "guò", 4, "experience particle; to pass", "我去过中国", "wǒ qùguo Zhōngguó", "I've been to China", "Function Words", 5),
    _c("得", "de", 5, "complement marker (verb+得+adj)", "跑得快", "pǎo de kuài", "runs fast", "Function Words", 5),
    _c("地", "de", 5, "adverb marker (adj+地+verb); ground", "高兴地说", "gāoxìng de shuō", "said happily", "Function Words", 5),
    _c("其", "qí", 2, "its; his; that (其他=other)", "其他人", "qítā rén", "other people", "Function Words", 5),
    _c("所", "suǒ", 3, "place; (所以=therefore)", "所以", "suǒyǐ", "therefore; so", "Function Words", 5),
    _c("而", "ér", 2, "and; but; yet (literary)", "而且", "érqiě", "and also; moreover", "Function Words", 5),
    _c("或", "huò", 4, "or; perhaps; maybe", "或者", "huòzhě", "or; perhaps", "Function Words", 5),

    # -- Week 6: Numbers --
    _c("一", "yī", 1, "one; a/an", "一个人", "yī gè rén", "one person", "Numbers", 6),
    _c("二", "èr", 4, "two", "二月", "èr yuè", "February", "Numbers", 6),
    _c("三", "sān", 1, "three", "三天", "sān tiān", "three days", "Numbers", 6),
    _c("四", "sì", 4, "four", "四点钟", "sì diǎn zhōng", "four o'clock", "Numbers", 6),
    _c("五", "wǔ", 3, "five", "五个", "wǔ gè", "five (of something)", "Numbers", 6),
    _c("六", "liù", 4, "six", "六月", "liù yuè", "June", "Numbers", 6),
    _c("七", "qī", 1, "seven", "一周七天", "yī zhōu qī tiān", "7 days in a week", "Numbers", 6),
    _c("八", "bā", 1, "eight", "八月", "bā yuè", "August", "Numbers", 6),
    _c("九", "jiǔ", 3, "nine", "九点", "jiǔ diǎn", "nine o'clock", "Numbers", 6),
    _c("十", "shí", 2, "ten", "十分钟", "shí fēnzhōng", "ten minutes", "Numbers", 6),
    _c("百", "bǎi", 3, "hundred", "一百块", "yī bǎi kuài", "100 yuan", "Numbers", 6),
    _c("千", "qiān", 1, "thousand", "一千人", "yī qiān rén", "1000 people", "Numbers", 6),

    # -- Week 7: Counting --
    _c("万", "wàn", 4, "ten thousand; myriad", "一万元", "yī wàn yuán", "10,000 yuan", "Counting", 7),
    _c("零", "líng", 2, "zero; remainder", "零下五度", "líng xià wǔ dù", "5 below zero", "Counting", 7),
    _c("两", "liǎng", 3, "two (with measure words); both", "两个人", "liǎng gè rén", "two people", "Counting", 7),
    _c("几", "jǐ", 3, "how many; several", "几个", "jǐ gè", "how many?", "Counting", 7),
    _c("多", "duō", 1, "many; much; more", "多少钱", "duōshǎo qián", "How much?", "Counting", 7),
    _c("少", "shǎo", 3, "few; little; scarce", "多少", "duōshǎo", "how many/much", "Counting", 7),
    _c("个", "gè", 4, "general measure word", "一个苹果", "yī gè píngguǒ", "an apple", "Counting", 7),
    _c("些", "xiē", 1, "some; a few (plural marker)", "这些书", "zhèxiē shū", "these books", "Counting", 7),
    _c("谁", "shuí", 2, "who; whom", "谁来了", "shuí lái le", "Who came?", "Question Words", 7),
    _c("哪", "nǎ", 3, "which; where (哪里=where)", "你去哪", "nǐ qù nǎ", "Where are you going?", "Question Words", 7),
    _c("怎", "zěn", 3, "how (怎么=how; 怎样=how)", "怎么办", "zěnme bàn", "What to do?", "Question Words", 7),
    _c("每", "měi", 3, "every; each", "每天", "měi tiān", "every day", "Question Words", 7),

    # -- Week 8: People --
    _c("人", "rén", 2, "person; people; human", "那个人", "nà gè rén", "that person", "People", 8),
    _c("家", "jiā", 1, "home; family; expert", "回家", "huí jiā", "go home", "People", 8),
    _c("子", "zǐ", 3, "son; child; suffix", "孩子", "háizi", "child/children", "People", 8),
    _c("女", "nǚ", 3, "woman; female; daughter", "女儿", "nǚér", "daughter", "People", 8),
    _c("父", "fù", 4, "father (formal)", "父母", "fùmǔ", "parents", "People", 8),
    _c("母", "mǔ", 3, "mother (formal)", "母亲", "mǔqīn", "mother", "People", 8),
    _c("男", "nán", 2, "male; man; boy", "男生", "nánshēng", "boy; male student", "Family", 8),
    _c("兄", "xiōng", 1, "older brother (formal)", "兄弟", "xiōngdì", "brothers", "Family", 8),
    _c("弟", "dì", 4, "younger brother", "弟弟", "dìdi", "younger brother", "Family", 8),
    _c("姐", "jiě", 3, "older sister", "姐姐", "jiějie", "older sister", "Family", 8),
    _c("妹", "mèi", 4, "younger sister", "妹妹", "mèimei", "younger sister", "Family", 8),
    _c("友", "yǒu", 3, "friend; friendly", "朋友", "péngyou", "friend", "Family", 8),

    # -- Week 9: Family --
    _c("爸", "bà", 4, "dad; father (informal)", "爸爸", "bàba", "dad", "Family", 9),
    _c("妈", "mā", 1, "mom; mother (informal)", "妈妈", "māma", "mom", "Family", 9),
    _c("哥", "gē", 1, "older brother (informal)", "哥哥", "gēge", "older brother", "Family", 9),
    _c("爷", "yé", 2, "grandfather (paternal)", "爷爷", "yéye", "grandpa (paternal)", "Family", 9),
    _c("奶", "nǎi", 3, "grandmother (paternal); milk", "奶奶", "nǎinai", "grandma (paternal)", "Family", 9),
    _c("朋", "péng", 2, "friend (part of 朋友)", "朋友们", "péngyoumen", "friends", "Family", 9),
    _c("先", "xiān", 1, "first; before; mister (先生)", "先生", "xiānsheng", "Mr.; sir; husband", "Titles", 9),
    _c("生", "shēng", 1, "born; life; student; raw", "学生", "xuésheng", "student", "Titles", 9),
    _c("老", "lǎo", 3, "old; elderly; always; very", "老师", "lǎoshī", "teacher", "Titles", 9),
    _c("师", "shī", 1, "teacher; master; expert", "老师好", "lǎoshī hǎo", "Hello, teacher!", "Titles", 9),
    _c("同", "tóng", 2, "same; together; with", "同学", "tóngxué", "classmate", "Titles", 9),
    _c("学", "xué", 2, "to study; to learn; school", "学中文", "xué Zhōngwén", "study Chinese", "Titles", 9),

    # -- Week 10: People --
    _c("孩", "hái", 2, "child (孩子=child)", "小孩", "xiǎohái", "little kid", "People", 10),
    _c("王", "wáng", 2, "king; (most common Chinese surname)", "王先生", "Wáng xiānsheng", "Mr. Wang", "People", 10),
    _c("姓", "xìng", 4, "surname; to be surnamed", "您贵姓", "nín guì xìng", "What's your surname?", "People", 10),
    _c("名", "míng", 2, "name; fame; famous", "名字", "míngzi", "name", "People", 10),
    _c("岁", "suì", 4, "years old; age", "你几岁", "nǐ jǐ suì", "How old are you?", "People", 10),
    _c("位", "wèi", 4, "polite measure word for people; seat", "这位是", "zhè wèi shì", "This (person) is...", "People", 10),
    _c("客", "kè", 4, "guest; visitor; customer", "客人", "kèrén", "guest; visitor", "People", 10),
    _c("叔", "shū", 1, "uncle (father's younger brother)", "叔叔", "shūshu", "uncle", "People", 10),
    _c("儿", "ér", 2, "son; child; suffix (儿化音)", "儿子", "érzi", "son", "People", 10),
    _c("夫", "fū", 1, "husband; man (丈夫=husband)", "丈夫", "zhàngfu", "husband", "People", 10),
    _c("妻", "qī", 1, "wife", "妻子", "qīzi", "wife", "People", 10),
    _c("您", "nín", 2, "you (polite/formal)", "您好", "nín hǎo", "Hello (formal)", "People", 10),

    # -- Week 11: Time --
    _c("年", "nián", 2, "year", "今年", "jīnnián", "this year", "Time", 11),
    _c("月", "yuè", 4, "month; moon", "这个月", "zhège yuè", "this month", "Time", 11),
    _c("日", "rì", 4, "day; sun; date", "生日", "shēngrì", "birthday", "Time", 11),
    _c("天", "tiān", 1, "day; sky; heaven; weather", "今天", "jīntiān", "today", "Time", 11),
    _c("时", "shí", 2, "time; hour; when", "小时", "xiǎoshí", "hour", "Time", 11),
    _c("今", "jīn", 1, "today; now; current", "今天天气好", "jīntiān tiānqì hǎo", "Nice weather today", "Time", 11),
    _c("明", "míng", 2, "tomorrow; bright; clear", "明天见", "míngtiān jiàn", "See you tomorrow", "Time", 11),
    _c("昨", "zuó", 2, "yesterday", "昨天", "zuótiān", "yesterday", "Time", 11),
    _c("早", "zǎo", 3, "early; morning; Good morning!", "早上好", "zǎoshang hǎo", "Good morning!", "Time", 11),
    _c("晚", "wǎn", 3, "evening; late; night", "晚上好", "wǎnshang hǎo", "Good evening!", "Time", 11),
    _c("前", "qián", 2, "front; before; ago", "三天前", "sān tiān qián", "three days ago", "Time", 11),
    _c("后", "hòu", 4, "after; behind; later", "以后", "yǐhòu", "after; in the future", "Time", 11),

    # -- Week 12: Time --
    _c("分", "fēn", 1, "minute; to divide; part", "十分钟", "shí fēnzhōng", "ten minutes", "Time", 12),
    _c("点", "diǎn", 3, "o'clock; dot; point; a little", "三点半", "sān diǎn bàn", "3:30 / half past three", "Time", 12),
    _c("钟", "zhōng", 1, "clock; bell; minute (分钟)", "一分钟", "yī fēnzhōng", "one minute", "Time", 12),
    _c("半", "bàn", 4, "half; semi-", "半天", "bàn tiān", "half a day / a long time", "Time", 12),
    _c("候", "hòu", 4, "to wait; time; season (时候)", "什么时候", "shénme shíhou", "When?", "Time", 12),
    _c("刻", "kè", 4, "quarter-hour; to carve; moment", "一刻钟", "yī kè zhōng", "fifteen minutes", "Time", 12),
    _c("周", "zhōu", 1, "week; to circle; Zhou (surname)", "上周", "shàng zhōu", "last week", "Time", 12),
    _c("期", "qī", 1, "period; phase (星期=week)", "星期一", "xīngqī yī", "Monday", "Time", 12),
    _c("春", "chūn", 1, "spring (season)", "春天", "chūntiān", "spring", "Seasons", 12),
    _c("夏", "xià", 4, "summer", "夏天", "xiàtiān", "summer", "Seasons", 12),
    _c("秋", "qiū", 1, "autumn; fall", "秋天", "qiūtiān", "autumn", "Seasons", 12),
    _c("冬", "dōng", 1, "winter", "冬天", "dōngtiān", "winter", "Seasons", 12),

    # -- Week 13: Time --
    _c("节", "jié", 2, "festival; holiday; section", "春节", "Chūn Jié", "Chinese New Year", "Time", 13),
    _c("假", "jià", 4, "holiday; vacation; fake", "放假", "fàngjià", "to have a holiday", "Time", 13),
    _c("久", "jiǔ", 3, "long (time); for a long time", "好久不见", "hǎo jiǔ bú jiàn", "Long time no see!", "Time", 13),
    _c("初", "chū", 1, "beginning; first; initial", "最初", "zuìchū", "at first; initially", "Time", 13),
    _c("午", "wǔ", 3, "noon; midday", "下午", "xiàwǔ", "afternoon", "Time", 13),
    _c("现", "xiàn", 4, "now; present; current; to appear", "现在", "xiànzài", "now; at present", "Time", 13),

    # -- Week 14: Directions --
    _c("上", "shàng", 4, "up; above; on top; last (week)", "桌子上", "zhuōzi shàng", "on the table", "Directions", 14),
    _c("下", "xià", 4, "down; below; under; next (week)", "下午", "xiàwǔ", "afternoon", "Directions", 14),
    _c("左", "zuǒ", 3, "left", "左边", "zuǒbiān", "left side", "Directions", 14),
    _c("右", "yòu", 4, "right", "右边", "yòubiān", "right side", "Directions", 14),
    _c("中", "zhōng", 1, "middle; center; China", "中间", "zhōngjiān", "in the middle", "Directions", 14),
    _c("里", "lǐ", 3, "inside; in; within", "房间里", "fángjiān lǐ", "inside the room", "Directions", 14),
    _c("外", "wài", 4, "outside; foreign; other", "外面", "wàimiàn", "outside", "Directions", 14),
    _c("东", "dōng", 1, "east", "东方", "dōngfāng", "the East", "Directions", 14),
    _c("西", "xī", 1, "west; (东西=thing)", "东西", "dōngxi", "thing(s)", "Directions", 14),
    _c("南", "nán", 2, "south", "南方", "nánfāng", "the South", "Directions", 14),
    _c("北", "běi", 3, "north", "北京", "Běijīng", "Beijing", "Directions", 14),
    _c("方", "fāng", 1, "direction; square; method", "地方", "dìfang", "place; location", "Directions", 14),

    # -- Week 15: Location --
    _c("间", "jiān", 1, "between; room; space", "房间", "fángjiān", "room", "Location", 15),
    _c("边", "biān", 1, "side; edge; (旁边=beside)", "旁边", "pángbiān", "beside; next to", "Location", 15),
    _c("旁", "páng", 2, "beside; side; nearby", "旁边", "pángbiān", "beside", "Location", 15),
    _c("近", "jìn", 4, "near; close", "很近", "hěn jìn", "very close", "Location", 15),
    _c("远", "yuǎn", 3, "far; distant; remote", "很远", "hěn yuǎn", "very far", "Location", 15),
    _c("面", "miàn", 4, "face; side; surface; noodles", "前面", "qiánmiàn", "in front", "Location", 15),

    # -- Week 16: Action Verbs --
    _c("来", "lái", 2, "to come", "请进来", "qǐng jìnlái", "Please come in", "Action Verbs", 16),
    _c("去", "qù", 4, "to go", "我去上学", "wǒ qù shàngxué", "I go to school", "Action Verbs", 16),
    _c("说", "shuō", 1, "to say; to speak; to tell", "他说中文", "tā shuō Zhōngwén", "He speaks Chinese", "Action Verbs", 16),
    _c("看", "kàn", 4, "to look; to watch; to read", "看电影", "kàn diànyǐng", "watch a movie", "Action Verbs", 16),
    _c("吃", "chī", 1, "to eat", "吃饭了吗", "chīfàn le ma", "Have you eaten?", "Action Verbs", 16),
    _c("喝", "hē", 1, "to drink", "喝茶", "hē chá", "drink tea", "Action Verbs", 16),
    _c("到", "dào", 4, "to arrive; to reach; until", "我到了", "wǒ dào le", "I've arrived", "Movement", 16),
    _c("出", "chū", 1, "to go out; to exit; to produce", "出去", "chūqù", "go out", "Movement", 16),
    _c("走", "zǒu", 3, "to walk; to leave; to go", "我们走吧", "wǒmen zǒu ba", "Let's go!", "Movement", 16),
    _c("开", "kāi", 1, "to open; to drive; to start", "开门", "kāi mén", "open the door", "Movement", 16),
    _c("回", "huí", 2, "to return; to go back; to reply", "回家", "huí jiā", "go home", "Movement", 16),
    _c("进", "jìn", 4, "to enter; to come/go in", "请进", "qǐng jìn", "Please come in", "Movement", 16),

    # -- Week 17: Action Verbs --
    _c("做", "zuò", 4, "to do; to make; to be", "做饭", "zuòfàn", "to cook", "Action Verbs", 17),
    _c("用", "yòng", 4, "to use; with; useful", "用筷子", "yòng kuàizi", "use chopsticks", "Action Verbs", 17),
    _c("买", "mǎi", 3, "to buy; to purchase", "买菜", "mǎi cài", "buy groceries", "Action Verbs", 17),
    _c("卖", "mài", 4, "to sell", "卖书", "mài shū", "sell books", "Action Verbs", 17),
    _c("找", "zhǎo", 3, "to find; to look for; to seek", "找人", "zhǎo rén", "look for someone", "Action Verbs", 17),
    _c("送", "sòng", 4, "to send; to give (a gift); to deliver", "送礼物", "sòng lǐwù", "give a gift", "Action Verbs", 17),
    _c("打", "dǎ", 3, "to hit; to make (a call); to play", "打电话", "dǎ diànhuà", "make a phone call", "Action Verbs", 17),
    _c("穿", "chuān", 1, "to wear; to put on; to pierce", "穿衣服", "chuān yīfu", "put on clothes", "Action Verbs", 17),
    _c("洗", "xǐ", 3, "to wash; to clean", "洗手", "xǐ shǒu", "wash hands", "Action Verbs", 17),
    _c("换", "huàn", 4, "to change; to exchange; to swap", "换衣服", "huàn yīfu", "change clothes", "Action Verbs", 17),
    _c("放", "fàng", 4, "to put; to place; to release; off (day)", "放下", "fàng xià", "put down; let go", "Action Verbs", 17),
    _c("拿", "ná", 2, "to take; to hold; to carry", "拿来", "ná lái", "bring (take-come)", "Action Verbs", 17),

    # -- Week 18: Movement --
    _c("跑", "pǎo", 3, "to run", "跑步", "pǎobù", "to jog; to run", "Movement", 18),
    _c("飞", "fēi", 1, "to fly", "飞机", "fēijī", "airplane", "Movement", 18),
    _c("游", "yóu", 2, "to swim; to travel; to tour", "游泳", "yóuyǒng", "to swim", "Movement", 18),
    _c("爬", "pá", 2, "to climb; to crawl", "爬山", "pá shān", "climb a mountain", "Movement", 18),
    _c("站", "zhàn", 4, "to stand; station; stop", "站起来", "zhàn qǐlái", "stand up", "Movement", 18),
    _c("坐", "zuò", 4, "to sit; to take (bus/train)", "坐下", "zuò xià", "sit down", "Movement", 18),
    _c("听", "tīng", 1, "to listen; to hear", "听音乐", "tīng yīnyuè", "listen to music", "Communication", 18),
    _c("问", "wèn", 4, "to ask; to inquire", "问问题", "wèn wèntí", "ask a question", "Communication", 18),
    _c("答", "dá", 2, "to answer; to reply", "回答", "huídá", "to answer; reply", "Communication", 18),
    _c("叫", "jiào", 4, "to call; to be called; to order", "我叫...", "wǒ jiào...", "My name is...", "Communication", 18),
    _c("请", "qǐng", 3, "please; to invite; to treat", "请问", "qǐngwèn", "Excuse me, may I ask...", "Communication", 18),
    _c("住", "zhù", 4, "to live; to stay; to reside", "住在北京", "zhù zài Běijīng", "live in Beijing", "Communication", 18),

    # -- Week 19: Action Verbs --
    _c("带", "dài", 4, "to bring; to carry; to wear (belt)", "带来", "dài lái", "bring (carry-come)", "Action Verbs", 19),
    _c("拉", "lā", 1, "to pull; to drag; to play (violin)", "拉门", "lā mén", "pull the door", "Action Verbs", 19),
    _c("推", "tuī", 1, "to push; to postpone", "推门", "tuī mén", "push the door", "Action Verbs", 19),
    _c("搬", "bān", 1, "to move (house/objects)", "搬家", "bān jiā", "to move house", "Action Verbs", 19),
    _c("举", "jǔ", 3, "to raise; to lift; to hold up", "举手", "jǔ shǒu", "raise your hand", "Action Verbs", 19),
    _c("接", "jiē", 1, "to receive; to pick up; to connect", "接电话", "jiē diànhuà", "answer the phone", "Action Verbs", 19),

    # -- Week 20: Cognitive --
    _c("想", "xiǎng", 3, "to think; to want; to miss", "我想你", "wǒ xiǎng nǐ", "I miss you", "Cognitive", 20),
    _c("知", "zhī", 1, "to know (a fact); knowledge", "知道", "zhīdào", "to know", "Cognitive", 20),
    _c("道", "dào", 4, "road; way; to say; (知道=know)", "知道了", "zhīdào le", "Got it / I know now", "Cognitive", 20),
    _c("认", "rèn", 4, "to recognize; to know (a person)", "认识", "rènshi", "to know (someone)", "Cognitive", 20),
    _c("识", "shí", 2, "to know; knowledge; to recognize", "认识你很高兴", "rènshi nǐ hěn gāoxìng", "Nice to meet you", "Cognitive", 20),
    _c("觉", "jué", 2, "to feel; to sense; sleep (睡觉)", "感觉", "gǎnjué", "feeling; to feel", "Cognitive", 20),
    _c("记", "jì", 4, "to remember; to record; to note", "记住", "jì zhù", "remember; memorize", "Learning", 20),
    _c("懂", "dǒng", 3, "to understand", "听懂了", "tīng dǒng le", "Understood (by listening)", "Learning", 20),
    _c("念", "niàn", 4, "to read aloud; to miss; to study", "念书", "niàn shū", "to study", "Learning", 20),
    _c("忘", "wàng", 4, "to forget", "别忘了", "bié wàng le", "Don't forget!", "Learning", 20),
    _c("思", "sī", 1, "to think; thought; to miss", "意思", "yìsi", "meaning; interesting", "Learning", 20),
    _c("决", "jué", 2, "to decide; to determine", "决定", "juédìng", "to decide; decision", "Learning", 20),

    # -- Week 21: Education --
    _c("读", "dú", 2, "to read; to study; reading", "读书", "dú shū", "to study; to read", "Education", 21),
    _c("写", "xiě", 3, "to write", "写字", "xiě zì", "write characters", "Education", 21),
    _c("教", "jiāo", 1, "to teach; to instruct", "教中文", "jiāo Zhōngwén", "teach Chinese", "Education", 21),
    _c("习", "xí", 2, "to practice; habit (学习=study)", "学习", "xuéxí", "to study; to learn", "Education", 21),
    _c("考", "kǎo", 3, "to test; exam; to examine", "考试", "kǎoshì", "exam; test", "Education", 21),
    _c("试", "shì", 4, "to try; test; exam (考试)", "试试", "shìshi", "give it a try", "Education", 21),
    _c("选", "xuǎn", 3, "to choose; to select; to elect", "选择", "xuǎnzé", "to choose; choice", "Education", 21),
    _c("择", "zé", 2, "to choose; to pick; to select", "选择题", "xuǎnzé tí", "multiple choice question", "Education", 21),
    _c("注", "zhù", 4, "to note; to pay attention; to pour", "注意", "zhùyì", "pay attention", "Education", 21),
    _c("意", "yì", 4, "meaning; intention; idea", "有意思", "yǒu yìsi", "interesting; fun", "Education", 21),
    _c("告", "gào", 4, "to tell; to inform; to announce", "告诉", "gàosu", "to tell", "Education", 21),
    _c("诉", "sù", 4, "to tell; to inform; to complain", "告诉我", "gàosu wǒ", "Tell me", "Education", 21),

    # -- Week 22: Adjectives --
    _c("大", "dà", 4, "big; large; great", "大学", "dàxué", "university", "Adjectives", 22),
    _c("小", "xiǎo", 3, "small; little; young", "小心", "xiǎoxīn", "be careful", "Adjectives", 22),
    _c("好", "hǎo", 3, "good; well; OK", "你好", "nǐ hǎo", "Hello!", "Adjectives", 22),
    _c("坏", "huài", 4, "bad; broken; spoiled", "手机坏了", "shǒujī huài le", "Phone is broken", "Adjectives", 22),
    _c("新", "xīn", 1, "new; fresh", "新年快乐", "xīnnián kuàilè", "Happy New Year!", "Adjectives", 22),
    _c("旧", "jiù", 4, "old; used; worn; former", "旧书", "jiù shū", "used book", "Adjectives", 22),
    _c("长", "cháng", 2, "long (length/time)", "很长时间", "hěn cháng shíjiān", "a very long time", "Adjectives", 22),
    _c("短", "duǎn", 3, "short (length/time)", "时间太短", "shíjiān tài duǎn", "too little time", "Adjectives", 22),
    _c("高", "gāo", 1, "tall; high; loud", "他很高", "tā hěn gāo", "He is very tall", "Adjectives", 22),
    _c("低", "dī", 1, "low; short (height)", "声音太低", "shēngyīn tài dī", "voice too low", "Adjectives", 22),
    _c("快", "kuài", 4, "fast; quick; soon; happy", "快来", "kuài lái", "Come quickly!", "Adjectives", 22),
    _c("慢", "màn", 4, "slow; slowly", "慢慢来", "mànmàn lái", "Take your time", "Adjectives", 22),

    # -- Week 23: Adjectives --
    _c("热", "rè", 4, "hot; warm; popular", "今天很热", "jīntiān hěn rè", "It's hot today", "Adjectives", 23),
    _c("冷", "lěng", 3, "cold; cool; indifferent", "外面很冷", "wàimiàn hěn lěng", "It's cold outside", "Adjectives", 23),
    _c("干", "gān", 1, "dry; clean; to do (干=gàn)", "干净", "gānjìng", "clean", "Adjectives", 23),
    _c("净", "jìng", 4, "clean; pure; only", "干净", "gānjìng", "clean; tidy", "Adjectives", 23),
    _c("难", "nán", 2, "difficult; hard; unpleasant", "很难", "hěn nán", "very difficult", "Adjectives", 23),
    _c("易", "yì", 4, "easy; simple (容易=easy)", "容易", "róngyì", "easy; simple", "Adjectives", 23),
    _c("贵", "guì", 4, "expensive; noble; your (polite)", "太贵了", "tài guì le", "Too expensive!", "Adjectives", 23),
    _c("胖", "pàng", 4, "fat; plump; chubby", "胖了", "pàng le", "gained weight", "Adjectives", 23),
    _c("瘦", "shòu", 4, "thin; skinny; lean", "很瘦", "hěn shòu", "very thin", "Adjectives", 23),
    _c("饿", "è", 4, "hungry", "我饿了", "wǒ è le", "I'm hungry", "Adjectives", 23),
    _c("渴", "kě", 3, "thirsty", "我渴了", "wǒ kě le", "I'm thirsty", "Adjectives", 23),
    _c("满", "mǎn", 3, "full; filled; satisfied", "满意", "mǎnyì", "satisfied", "Adjectives", 23),

    # -- Week 24: Adjectives --
    _c("亮", "liàng", 4, "bright; shiny; clear", "漂亮", "piàoliang", "beautiful; pretty", "Adjectives", 24),
    _c("美", "měi", 3, "beautiful; fine; America", "美丽", "měilì", "beautiful", "Adjectives", 24),
    _c("丑", "chǒu", 3, "ugly; shameful", "很丑", "hěn chǒu", "very ugly", "Adjectives", 24),
    _c("忙", "máng", 2, "busy; hurried", "我很忙", "wǒ hěn máng", "I'm very busy", "Adjectives", 24),
    _c("累", "lèi", 4, "tired; weary; tiring", "累死了", "lèi sǐ le", "exhausted", "Adjectives", 24),
    _c("安", "ān", 1, "safe; peaceful; calm; to install", "安全", "ānquán", "safe; safety", "Adjectives", 24),
    _c("静", "jìng", 4, "quiet; calm; still", "安静", "ānjìng", "quiet; peaceful", "Adjectives", 24),
    _c("简", "jiǎn", 3, "simple; brief; to simplify", "简单", "jiǎndān", "simple; easy", "Adjectives", 24),
    _c("单", "dān", 1, "single; simple; alone; list", "简单", "jiǎndān", "simple", "Adjectives", 24),
    _c("清", "qīng", 1, "clear; clean; pure; Qing dynasty", "清楚", "qīngchu", "clear; clearly", "Adjectives", 24),
    _c("楚", "chǔ", 3, "clear; tidy (清楚=clear)", "清清楚楚", "qīngqīng chǔchǔ", "crystal clear", "Adjectives", 24),
    _c("整", "zhěng", 3, "whole; entire; to arrange; neat", "整天", "zhěng tiān", "all day long", "Adjectives", 24),

    # -- Week 25: Colors --
    _c("红", "hóng", 2, "red; popular; lucky", "红色", "hóngsè", "red (color)", "Colors", 25),
    _c("白", "bái", 2, "white; plain; blank; in vain", "白色", "báisè", "white", "Colors", 25),
    _c("黑", "hēi", 1, "black; dark", "黑色", "hēisè", "black", "Colors", 25),
    _c("蓝", "lán", 2, "blue", "蓝天", "lán tiān", "blue sky", "Colors", 25),
    _c("绿", "lǜ", 4, "green", "绿色", "lǜsè", "green", "Colors", 25),
    _c("黄", "huáng", 2, "yellow", "黄色", "huángsè", "yellow", "Colors", 25),
    _c("水", "shuǐ", 3, "water", "喝水", "hē shuǐ", "drink water", "Nature", 25),
    _c("火", "huǒ", 3, "fire; flame; angry", "火车", "huǒchē", "train", "Nature", 25),
    _c("山", "shān", 1, "mountain; hill", "爬山", "pá shān", "climb a mountain", "Nature", 25),
    _c("木", "mù", 4, "wood; tree; wooden", "木头", "mùtou", "wood; log", "Nature", 25),
    _c("土", "tǔ", 3, "earth; soil; land; local", "土地", "tǔdì", "land; soil", "Nature", 25),
    _c("花", "huā", 1, "flower; to spend (money/time)", "买花", "mǎi huā", "buy flowers", "Nature", 25),

    # -- Week 26: Nature --
    _c("草", "cǎo", 3, "grass; plant; rough", "草地", "cǎodì", "grassland; lawn", "Nature", 26),
    _c("树", "shù", 4, "tree", "树上有鸟", "shù shàng yǒu niǎo", "Birds in the tree", "Nature", 26),
    _c("雨", "yǔ", 3, "rain", "下雨了", "xià yǔ le", "It's raining", "Weather", 26),
    _c("风", "fēng", 1, "wind; style; custom", "风很大", "fēng hěn dà", "Strong wind", "Weather", 26),
    _c("雪", "xuě", 3, "snow", "下雪了", "xià xuě le", "It's snowing", "Weather", 26),
    _c("云", "yún", 2, "cloud", "白云", "báiyún", "white cloud", "Weather", 26),
    _c("河", "hé", 2, "river", "河水", "hé shuǐ", "river water", "Nature", 26),
    _c("海", "hǎi", 3, "sea; ocean", "大海", "dà hǎi", "the sea; ocean", "Nature", 26),
    _c("叶", "yè", 4, "leaf", "树叶", "shùyè", "tree leaf", "Nature", 26),
    _c("阳", "yáng", 2, "sun; solar; positive; male", "太阳", "tàiyáng", "the sun", "Nature", 26),
    _c("阴", "yīn", 1, "cloudy; overcast; shade; lunar", "阴天", "yīn tiān", "cloudy day", "Weather", 26),
    _c("晴", "qíng", 2, "clear; sunny (weather)", "晴天", "qíng tiān", "sunny day", "Weather", 26),

    # -- Week 27: Nature --
    _c("鸟", "niǎo", 3, "bird", "小鸟", "xiǎo niǎo", "little bird", "Nature", 27),
    _c("石", "shí", 2, "stone; rock", "石头", "shítou", "stone; rock", "Nature", 27),
    _c("景", "jǐng", 3, "scenery; view; scene", "风景", "fēngjǐng", "scenery; landscape", "Nature", 27),
    _c("环", "huán", 2, "ring; loop; (环境=environment)", "环境", "huánjìng", "environment", "Nature", 27),
    _c("境", "jìng", 4, "border; territory; environment", "环境很好", "huánjìng hěn hǎo", "Nice environment", "Nature", 27),
    _c("气", "qì", 4, "air; gas; energy; angry; weather", "天气", "tiānqì", "weather", "Nature", 27),
    _c("手", "shǒu", 3, "hand; expert at sth", "洗手", "xǐ shǒu", "wash hands", "Body", 27),
    _c("口", "kǒu", 3, "mouth; opening; entrance", "入口", "rùkǒu", "entrance", "Body", 27),
    _c("眼", "yǎn", 3, "eye", "眼睛", "yǎnjing", "eye(s)", "Body", 27),
    _c("耳", "ěr", 3, "ear", "耳朵", "ěrduo", "ear(s)", "Body", 27),
    _c("心", "xīn", 1, "heart; mind; center", "小心", "xiǎoxīn", "be careful", "Body", 27),
    _c("头", "tóu", 2, "head; top; first", "头疼", "tóuténg", "headache", "Body", 27),

    # -- Week 28: Body --
    _c("脚", "jiǎo", 3, "foot", "脚疼", "jiǎo téng", "foot hurts", "Body", 28),
    _c("身", "shēn", 1, "body; oneself", "身体", "shēntǐ", "body; health", "Body", 28),
    _c("背", "bèi", 4, "back; to carry; to memorize", "背包", "bēibāo", "backpack", "Body", 28),
    _c("腿", "tuǐ", 3, "leg", "腿很长", "tuǐ hěn cháng", "long legs", "Body", 28),
    _c("鼻", "bí", 2, "nose", "鼻子", "bízi", "nose", "Body", 28),
    _c("嘴", "zuǐ", 3, "mouth; lips", "嘴巴", "zuǐba", "mouth (colloquial)", "Body", 28),
    _c("病", "bìng", 4, "sick; illness; disease", "生病了", "shēng bìng le", "got sick", "Health", 28),
    _c("药", "yào", 4, "medicine; drug; cure", "吃药", "chī yào", "take medicine", "Health", 28),
    _c("疼", "téng", 2, "painful; to ache; to love dearly", "头疼", "tóu téng", "headache", "Health", 28),
    _c("体", "tǐ", 3, "body; form; style; substance", "身体好", "shēntǐ hǎo", "in good health", "Health", 28),
    _c("医", "yī", 1, "medicine; medical; doctor", "医生", "yīshēng", "doctor", "Health", 28),
    _c("院", "yuàn", 4, "courtyard; institution; hospital", "医院", "yīyuàn", "hospital", "Health", 28),

    # -- Week 29: Food --
    _c("饭", "fàn", 4, "cooked rice; meal; food", "吃饭", "chīfàn", "eat a meal", "Food", 29),
    _c("茶", "chá", 2, "tea", "喝茶", "hē chá", "drink tea", "Food", 29),
    _c("酒", "jiǔ", 3, "alcohol; wine; liquor", "喝酒", "hē jiǔ", "drink alcohol", "Food", 29),
    _c("米", "mǐ", 3, "rice (uncooked); meter", "米饭", "mǐfàn", "cooked rice", "Food", 29),
    _c("肉", "ròu", 4, "meat; flesh", "猪肉", "zhūròu", "pork", "Food", 29),
    _c("菜", "cài", 4, "vegetable; dish; food", "中国菜", "Zhōngguó cài", "Chinese food", "Food", 29),
    _c("鸡", "jī", 1, "chicken", "鸡肉", "jīròu", "chicken meat", "Food", 29),
    _c("蛋", "dàn", 4, "egg", "鸡蛋", "jīdàn", "egg", "Food", 29),
    _c("豆", "dòu", 4, "bean; pea; legume", "豆腐", "dòufu", "tofu", "Food", 29),
    _c("果", "guǒ", 3, "fruit; result", "水果", "shuǐguǒ", "fruit", "Food", 29),
    _c("糖", "táng", 2, "sugar; candy; sweet", "糖果", "tángguǒ", "candy", "Food", 29),
    _c("牛", "niú", 2, "cow; cattle; ox; stubborn", "牛肉", "niúròu", "beef", "Food", 29),

    # -- Week 30: Food --
    _c("羊", "yáng", 2, "sheep; goat; lamb", "羊肉", "yángròu", "lamb/mutton", "Food", 30),
    _c("苹", "píng", 2, "apple (part of 苹果)", "苹果", "píngguǒ", "apple", "Food", 30),
    _c("杯", "bēi", 1, "cup; glass; (measure word)", "一杯茶", "yī bēi chá", "a cup of tea", "Food", 30),
    _c("碗", "wǎn", 3, "bowl", "一碗饭", "yī wǎn fàn", "a bowl of rice", "Food", 30),
    _c("瓶", "píng", 2, "bottle", "一瓶水", "yī píng shuǐ", "a bottle of water", "Food", 30),
    _c("盘", "pán", 2, "plate; dish; tray", "一盘菜", "yī pán cài", "a plate of food", "Food", 30),
    _c("衣", "yī", 1, "clothing; garment (衣服=clothes)", "衣服", "yīfu", "clothes", "Clothing", 30),
    _c("服", "fú", 2, "clothing; to serve; to obey", "穿衣服", "chuān yīfu", "wear clothes", "Clothing", 30),
    _c("鞋", "xié", 2, "shoes", "穿鞋", "chuān xié", "put on shoes", "Clothing", 30),
    _c("帽", "mào", 4, "hat; cap", "帽子", "màozi", "hat", "Clothing", 30),
    _c("裤", "kù", 4, "pants; trousers", "裤子", "kùzi", "pants", "Clothing", 30),
    _c("裙", "qún", 2, "skirt; dress", "裙子", "qúnzi", "skirt; dress", "Clothing", 30),

    # -- Week 31: Home --
    _c("房", "fáng", 2, "house; room; building", "房间", "fángjiān", "room", "Home", 31),
    _c("门", "mén", 2, "door; gate; entrance", "开门", "kāi mén", "open the door", "Home", 31),
    _c("窗", "chuāng", 1, "window", "窗户", "chuānghù", "window", "Home", 31),
    _c("桌", "zhuō", 1, "table; desk", "桌子", "zhuōzi", "table", "Home", 31),
    _c("椅", "yǐ", 3, "chair", "椅子", "yǐzi", "chair", "Home", 31),
    _c("床", "chuáng", 2, "bed", "上床睡觉", "shàng chuáng shuìjiào", "go to bed", "Home", 31),
    _c("灯", "dēng", 1, "light; lamp", "开灯", "kāi dēng", "turn on the light", "Home", 31),
    _c("楼", "lóu", 2, "floor; story; building", "一楼", "yī lóu", "first floor", "Home", 31),
    _c("层", "céng", 2, "floor (measure word); layer", "三层楼", "sān céng lóu", "three-story building", "Home", 31),
    _c("厨", "chú", 2, "kitchen (厨房=kitchen)", "厨房", "chúfáng", "kitchen", "Home", 31),
    _c("刀", "dāo", 1, "knife; blade", "小刀", "xiǎo dāo", "small knife", "Home", 31),
    _c("伞", "sǎn", 3, "umbrella", "带伞", "dài sǎn", "bring an umbrella", "Home", 31),

    # -- Week 32: Transport --
    _c("车", "chē", 1, "vehicle; car; train", "坐车", "zuò chē", "ride a vehicle", "Transport", 32),
    _c("路", "lù", 4, "road; path; route", "一路平安", "yī lù píng'ān", "Safe journey!", "Transport", 32),
    _c("城", "chéng", 2, "city; town; wall", "城市", "chéngshì", "city", "Transport", 32),
    _c("店", "diàn", 4, "shop; store; inn", "书店", "shūdiàn", "bookstore", "Transport", 32),
    _c("市", "shì", 4, "city; market; urban", "超市", "chāoshì", "supermarket", "Transport", 32),
    _c("街", "jiē", 1, "street; road", "逛街", "guàng jiē", "go shopping / window-shop", "Transport", 32),
    _c("船", "chuán", 2, "boat; ship", "坐船", "zuò chuán", "take a boat", "Transport", 32),
    _c("票", "piào", 4, "ticket; ballot; note", "买票", "mǎi piào", "buy a ticket", "Transport", 32),
    _c("租", "zū", 1, "to rent; to hire", "出租车", "chūzūchē", "taxi", "Transport", 32),
    _c("场", "chǎng", 3, "field; ground; venue; site", "机场", "jīchǎng", "airport", "Transport", 32),
    _c("公", "gōng", 1, "public; male; official; fair", "公共汽车", "gōnggòng qìchē", "bus", "Transport", 32),
    _c("司", "sī", 1, "to manage; department (公司=company)", "公司", "gōngsī", "company", "Transport", 32),

    # -- Week 33: Places --
    _c("旅", "lǚ", 3, "to travel; trip; journey", "旅游", "lǚyóu", "to travel; tourism", "Places", 33),
    _c("铁", "tiě", 3, "iron; hard (地铁=subway)", "地铁", "dìtiě", "subway", "Places", 33),
    _c("桥", "qiáo", 2, "bridge", "过桥", "guò qiáo", "cross a bridge", "Places", 33),
    _c("运", "yùn", 4, "to transport; luck; fate", "运动", "yùndòng", "exercise; sports", "Places", 33),
    _c("动", "dòng", 4, "to move; action; movement", "运动", "yùndòng", "exercise; sports", "Places", 33),
    _c("步", "bù", 4, "step; pace; foot; to walk", "跑步", "pǎobù", "to jog", "Places", 33),
    _c("校", "xiào", 4, "school", "学校", "xuéxiào", "school", "Places", 33),
    _c("馆", "guǎn", 3, "hall; building; hotel; restaurant", "图书馆", "túshūguǎn", "library", "Places", 33),
    _c("宾", "bīn", 1, "guest (宾馆=hotel)", "宾馆", "bīnguǎn", "hotel", "Places", 33),
    _c("办", "bàn", 4, "to do; to handle; to manage", "办公室", "bàngōngshì", "office", "Places", 33),
    _c("园", "yuán", 2, "garden; park; yard", "公园", "gōngyuán", "park", "Places", 33),
    _c("商", "shāng", 1, "business; commerce; merchant", "商店", "shāngdiàn", "shop; store", "Places", 33),

    # -- Week 34: Places --
    _c("村", "cūn", 1, "village", "农村", "nóngcūn", "countryside; rural area", "Places", 34),
    _c("区", "qū", 1, "area; district; zone", "小区", "xiǎoqū", "residential area", "Places", 34),
    _c("世", "shì", 4, "world; era; generation (世界)", "世界", "shìjiè", "the world", "Places", 34),
    _c("界", "jiè", 4, "boundary; world; field", "世界", "shìjiè", "the world", "Places", 34),
    _c("京", "jīng", 1, "capital (city); Beijing", "北京", "Běijīng", "Beijing", "Places", 34),
    _c("国", "guó", 2, "country; nation; national", "中国", "Zhōngguó", "China", "Places", 34),
    _c("银", "yín", 2, "silver; money; bank (银行)", "银行", "yínháng", "bank", "Places", 34),
    _c("行", "xíng", 2, "to walk; OK; bank (银行=yínháng)", "行不行", "xíng bu xíng", "Is that OK?", "Places", 34),
    _c("室", "shì", 4, "room; office; studio", "教室", "jiàoshì", "classroom", "Places", 34),
    _c("图", "tú", 2, "picture; map; drawing; plan", "地图", "dìtú", "map", "Places", 34),
    _c("广", "guǎng", 3, "wide; broad; extensive", "广场", "guǎngchǎng", "public square; plaza", "Places", 34),

    # -- Week 35: Education --
    _c("课", "kè", 4, "class; lesson; course", "上课", "shàng kè", "attend class", "Education", 35),
    _c("题", "tí", 2, "topic; question; problem; title", "问题", "wèntí", "question; problem", "Education", 35),
    _c("级", "jí", 2, "level; grade; rank; class", "年级", "niánjí", "grade (in school)", "Education", 35),
    _c("文", "wén", 2, "language; culture; writing", "中文", "Zhōngwén", "Chinese language", "Education", 35),
    _c("字", "zì", 4, "character; word; letter", "汉字", "Hànzì", "Chinese characters", "Education", 35),
    _c("语", "yǔ", 3, "language; speech; words", "英语", "Yīngyǔ", "English language", "Education", 35),
    _c("本", "běn", 3, "root; this; book (measure word)", "一本书", "yī běn shū", "a book", "Education", 35),
    _c("笔", "bǐ", 3, "pen; writing tool", "铅笔", "qiānbǐ", "pencil", "Education", 35),
    _c("纸", "zhǐ", 3, "paper", "一张纸", "yī zhāng zhǐ", "a sheet of paper", "Education", 35),
    _c("报", "bào", 4, "newspaper; report; to report", "报纸", "bàozhǐ", "newspaper", "Education", 35),
    _c("言", "yán", 2, "speech; words; to say", "语言", "yǔyán", "language", "Education", 35),
    _c("书", "shū", 1, "book; letter; document", "看书", "kàn shū", "read a book", "Education", 35),

    # -- Week 36: Work --
    _c("工", "gōng", 1, "work; labor; craft", "工作", "gōngzuò", "work; job", "Work", 36),
    _c("作", "zuò", 4, "to do; to make; work", "工作", "gōngzuò", "work; job", "Work", 36),
    _c("业", "yè", 4, "industry; business; profession", "毕业", "bìyè", "to graduate", "Work", 36),
    _c("钱", "qián", 2, "money; coin", "多少钱", "duōshǎo qián", "How much?", "Work", 36),
    _c("块", "kuài", 4, "piece; chunk; yuan (money)", "一块钱", "yī kuài qián", "one yuan", "Work", 36),
    _c("元", "yuán", 2, "yuan (currency); first; primary", "十元", "shí yuán", "ten yuan", "Work", 36),
    _c("爱", "ài", 4, "to love; love; affection", "我爱你", "wǒ ài nǐ", "I love you", "Emotions", 36),
    _c("恨", "hèn", 4, "to hate; hatred; regret", "很恨", "hěn hèn", "really hate", "Emotions", 36),
    _c("笑", "xiào", 4, "to laugh; to smile", "笑一笑", "xiào yi xiào", "Smile a little!", "Emotions", 36),
    _c("哭", "kū", 1, "to cry; to weep", "别哭了", "bié kū le", "Stop crying", "Emotions", 36),
    _c("怕", "pà", 4, "to fear; afraid; perhaps", "我怕蛇", "wǒ pà shé", "I'm afraid of snakes", "Emotions", 36),
    _c("急", "jí", 2, "urgent; anxious; impatient", "不急", "bù jí", "No rush", "Emotions", 36),

    # -- Week 37: Emotions --
    _c("欢", "huān", 1, "happy; joyful (喜欢=to like)", "喜欢", "xǐhuān", "to like", "Emotions", 37),
    _c("喜", "xǐ", 3, "happy; to like; joy (喜欢)", "喜欢你", "xǐhuān nǐ", "I like you", "Emotions", 37),
    _c("兴", "xìng", 4, "interest; excited (高兴=happy)", "高兴", "gāoxìng", "happy; glad", "Emotions", 37),
    _c("乐", "lè", 4, "happy; joyful; music (yuè)", "快乐", "kuàilè", "happy; joyful", "Emotions", 37),
    _c("望", "wàng", 4, "to hope; to gaze; hope", "希望", "xīwàng", "to hope; hope", "Emotions", 37),
    _c("希", "xī", 1, "hope; to hope (希望)", "希望你好", "xīwàng nǐ hǎo", "Hope you're well", "Emotions", 37),
    _c("感", "gǎn", 3, "to feel; to sense; grateful", "感觉", "gǎnjué", "feeling; to feel", "Emotions", 37),
    _c("情", "qíng", 2, "feeling; emotion; situation", "感情", "gǎnqíng", "feelings; emotion", "Emotions", 37),
    _c("担", "dān", 1, "to carry; to worry (担心)", "担心", "dānxīn", "to worry; worried", "Emotions", 37),
    _c("谢", "xiè", 4, "to thank; thanks; to decline", "谢谢", "xièxie", "Thank you!", "Emotions", 37),
    _c("错", "cuò", 4, "wrong; mistake; error", "没错", "méi cuò", "That's right / No mistake", "Emotions", 37),
    _c("关", "guān", 1, "to close; to turn off; to concern", "关心", "guānxīn", "to care about", "Emotions", 37),

    # -- Week 38: Verbs --
    _c("见", "jiàn", 4, "to see; to meet; to appear", "再见", "zàijiàn", "Goodbye", "Verbs", 38),
    _c("系", "xì", 4, "system; department; to tie", "没关系", "méi guānxì", "It doesn't matter", "Verbs", 38),
    _c("完", "wán", 2, "to finish; complete; whole", "做完了", "zuò wán le", "Done; finished", "Verbs", 38),
    _c("成", "chéng", 2, "to become; to succeed; OK", "成功", "chénggōng", "success; to succeed", "Verbs", 38),
    _c("变", "biàn", 4, "to change; to become; to vary", "变化", "biànhuà", "change; variation", "Verbs", 38),
    _c("需", "xū", 1, "to need; must; requirement", "需要", "xūyào", "to need; requirement", "Verbs", 38),
    _c("准", "zhǔn", 3, "accurate; to allow; standard", "准备", "zhǔnbèi", "to prepare; ready", "Verbs", 38),
    _c("备", "bèi", 4, "to prepare; equipment; ready", "准备好了", "zhǔnbèi hǎo le", "Ready!", "Verbs", 38),
    _c("参", "cān", 1, "to participate; to join (参加)", "参加", "cānjiā", "to participate; attend", "Verbs", 38),
    _c("加", "jiā", 1, "to add; to join; plus", "参加活动", "cānjiā huódòng", "join an activity", "Verbs", 38),
    _c("入", "rù", 4, "to enter; to join; into", "进入", "jìnrù", "to enter (formal)", "Verbs", 38),
    _c("帮", "bāng", 1, "to help; to assist", "帮忙", "bāngmáng", "to help; do a favor", "Verbs", 38),

    # -- Week 39: Daily Verbs --
    _c("睡", "shuì", 4, "to sleep", "睡觉", "shuìjiào", "to sleep", "Daily Verbs", 39),
    _c("起", "qǐ", 3, "to rise; to get up; to start", "起床", "qǐchuáng", "get out of bed", "Daily Verbs", 39),
    _c("等", "děng", 3, "to wait; rank; class; etc.", "等一下", "děng yīxià", "Wait a moment", "Daily Verbs", 39),
    _c("唱", "chàng", 4, "to sing", "唱歌", "chàng gē", "to sing (a song)", "Daily Verbs", 39),
    _c("跳", "tiào", 4, "to jump; to dance; to skip", "跳舞", "tiào wǔ", "to dance", "Daily Verbs", 39),
    _c("玩", "wán", 2, "to play; to have fun; to visit", "玩游戏", "wán yóuxì", "play games", "Daily Verbs", 39),
    _c("画", "huà", 4, "to draw; painting; picture", "画画", "huà huà", "to draw/paint", "Daily Verbs", 39),
    _c("骑", "qí", 2, "to ride (horse/bike)", "骑自行车", "qí zìxíngchē", "ride a bicycle", "Daily Verbs", 39),
    _c("踢", "tī", 1, "to kick; to play (soccer)", "踢足球", "tī zúqiú", "play soccer", "Daily Verbs", 39),
    _c("拍", "pāi", 1, "to clap; to film; to hit", "拍照", "pāi zhào", "take a photo", "Daily Verbs", 39),
    _c("搞", "gǎo", 3, "to do; to make; to handle", "搞定了", "gǎo dìng le", "Got it done!", "Daily Verbs", 39),
    _c("像", "xiàng", 4, "to resemble; like; image", "好像", "hǎoxiàng", "it seems like", "Daily Verbs", 39),

    # -- Week 40: Technology --
    _c("电", "diàn", 4, "electricity; electric", "电脑", "diànnǎo", "computer", "Technology", 40),
    _c("话", "huà", 4, "speech; words; conversation", "打电话", "dǎ diànhuà", "make a call", "Technology", 40),
    _c("机", "jī", 1, "machine; opportunity; airplane", "手机", "shǒujī", "phone", "Technology", 40),
    _c("网", "wǎng", 3, "net; internet; network", "上网", "shàng wǎng", "go online", "Technology", 40),
    _c("脑", "nǎo", 3, "brain; mind (电脑=computer)", "电脑", "diànnǎo", "computer", "Technology", 40),
    _c("视", "shì", 4, "to look; vision (电视=TV)", "电视", "diànshì", "television", "Technology", 40),
    _c("影", "yǐng", 3, "shadow; movie; image", "电影", "diànyǐng", "movie; film", "Technology", 40),
    _c("信", "xìn", 4, "letter; to believe; trust; faith", "相信", "xiāngxìn", "to believe", "Technology", 40),
    _c("照", "zhào", 4, "to shine; photo; according to", "照片", "zhàopiàn", "photograph", "Technology", 40),
    _c("片", "piàn", 4, "slice; piece; film; (照片=photo)", "照片", "zhàopiàn", "photograph", "Technology", 40),
    _c("号", "hào", 4, "number; date; mark; size", "电话号码", "diànhuà hàomǎ", "phone number", "Technology", 40),
    _c("音", "yīn", 1, "sound; voice; tone; music", "音乐", "yīnyuè", "music", "Technology", 40),

    # -- Week 41: Objects --
    _c("色", "sè", 4, "color; look; type", "颜色", "yánsè", "color", "Objects", 41),
    _c("件", "jiàn", 4, "item; piece (measure word)", "一件事", "yī jiàn shì", "one thing/matter", "Objects", 41),
    _c("条", "tiáo", 2, "strip; (measure for long things)", "一条路", "yī tiáo lù", "a road", "Objects", 41),
    _c("张", "zhāng", 1, "measure for flat things; to open", "一张纸", "yī zhāng zhǐ", "a sheet of paper", "Objects", 41),
    _c("双", "shuāng", 1, "pair; double; both; even (number)", "一双鞋", "yī shuāng xié", "a pair of shoes", "Objects", 41),
    _c("辆", "liàng", 4, "measure word for vehicles", "一辆车", "yī liàng chē", "a vehicle", "Objects", 41),
    _c("化", "huà", 4, "change; -ize; culture (文化)", "变化", "biànhuà", "change; variation", "Society", 41),
    _c("民", "mín", 2, "people; citizen; folk", "人民", "rénmín", "the people", "Society", 41),
    _c("法", "fǎ", 3, "law; method; way; France", "方法", "fāngfǎ", "method; way", "Society", 41),
    _c("历", "lì", 4, "history; experience; calendar", "历史", "lìshǐ", "history", "Society", 41),
    _c("史", "shǐ", 3, "history; annals", "历史", "lìshǐ", "history", "Society", 41),

    # -- Week 42: Society --
    _c("汉", "hàn", 4, "Han Chinese; man; Chinese", "汉语", "Hànyǔ", "Chinese language", "Society", 42),
    _c("介", "jiè", 4, "to introduce; between", "介绍", "jièshào", "to introduce", "Society", 42),
    _c("绍", "shào", 4, "to introduce; to continue", "自我介绍", "zìwǒ jièshào", "self-introduction", "Society", 42),
    _c("迎", "yíng", 2, "to welcome; to meet; to face", "欢迎光临", "huānyíng guānglín", "Welcome!", "Society", 42),
    _c("共", "gòng", 4, "common; shared; altogether", "一共", "yīgòng", "altogether; in total", "Society", 42),
    _c("提", "tí", 2, "to raise; to mention; to carry", "提问", "tíwèn", "to ask a question", "Society", 42),
    _c("管", "guǎn", 3, "to manage; tube; pipe; regardless", "不管", "bùguǎn", "no matter; regardless", "Society", 42),
    _c("事", "shì", 4, "matter; thing; affair; event", "没事", "méi shì", "It's nothing / I'm fine", "Society", 42),
    _c("理", "lǐ", 3, "reason; logic; to manage; physics", "道理", "dàolǐ", "reason; principle", "Society", 42),
    _c("力", "lì", 4, "power; strength; force; ability", "努力", "nǔlì", "to work hard; effort", "Society", 42),
    _c("主", "zhǔ", 3, "main; master; owner; host", "主要", "zhǔyào", "main; primary", "Society", 42),

    # -- Week 43: Abstract --
    _c("定", "dìng", 4, "to fix; to decide; certain", "一定", "yīdìng", "definitely; certainly", "Abstract", 43),
    _c("种", "zhǒng", 3, "kind; type; seed; to plant", "这种", "zhè zhǒng", "this kind/type", "Abstract", 43),
    _c("样", "yàng", 4, "shape; type; way; (怎么样=how)", "一样", "yīyàng", "the same", "Abstract", 43),
    _c("然", "rán", 2, "so; like that; (当然=of course)", "当然", "dāngrán", "of course", "Abstract", 43),
    _c("当", "dāng", 1, "to be; to serve as; when; should", "当然", "dāngrán", "of course", "Abstract", 43),
    _c("因", "yīn", 1, "because; reason; cause", "因为", "yīnwèi", "because", "Abstract", 43),
    _c("虽", "suī", 1, "although; even though (虽然)", "虽然", "suīrán", "although", "Abstract", 43),
    _c("但", "dàn", 4, "but; however; only", "但是", "dànshì", "but; however", "Abstract", 43),
    _c("如", "rú", 2, "as if; like; if; such as", "如果", "rúguǒ", "if; in case", "Abstract", 43),
    _c("正", "zhèng", 4, "just; right; correct; straight", "正在", "zhèngzài", "right now; in the middle of", "Abstract", 43),
    _c("真", "zhēn", 1, "real; true; genuine; really", "真的吗", "zhēn de ma", "Really?", "Abstract", 43),

    # -- Week 44: Function Words --
    _c("只", "zhǐ", 3, "only; just; merely", "只有", "zhǐyǒu", "only; only if", "Function Words", 44),
    _c("别", "bié", 2, "don't; other; to leave", "别走", "bié zǒu", "Don't go!", "Function Words", 44),
    _c("另", "lìng", 4, "other; another; separate", "另外", "lìngwài", "in addition; other", "Function Words", 44),
    _c("自", "zì", 4, "self; from; since; naturally", "自己", "zìjǐ", "oneself", "Function Words", 44),
    _c("己", "jǐ", 3, "self; oneself (自己)", "自己做", "zìjǐ zuò", "do it yourself", "Function Words", 44),
    _c("特", "tè", 4, "special; particular; especially", "特别", "tèbié", "especially; special", "Function Words", 44),
    _c("且", "qiě", 3, "and; moreover; for the time being", "而且", "érqiě", "moreover", "Function Words", 44),
    _c("除", "chú", 2, "to remove; except; besides; to divide", "除了", "chúle", "except for; besides", "Function Words", 44),
    _c("根", "gēn", 1, "root; basis; (根据=according to)", "根据", "gēnjù", "according to; based on", "Function Words", 44),
    _c("据", "jù", 4, "according to; evidence; to occupy", "根据", "gēnjù", "according to", "Function Words", 44),

    # -- Week 45: Sequence --
    _c("终", "zhōng", 1, "end; final; eventually", "最终", "zuìzhōng", "finally; in the end", "Sequence", 45),
    _c("总", "zǒng", 3, "always; overall; general; total", "总是", "zǒngshì", "always", "Sequence", 45),

    # -- Week 46: Geography --
    _c("省", "shěng", 3, "province; to save; to omit", "省钱", "shěng qián", "save money", "Geography", 46),
    _c("镇", "zhèn", 4, "town; to calm; to suppress", "小镇", "xiǎo zhèn", "small town", "Geography", 46),
    _c("农", "nóng", 2, "agriculture; farming; farmer", "农村", "nóngcūn", "countryside", "Geography", 46),
    _c("平", "píng", 2, "flat; level; peaceful; ordinary", "平安", "píng'ān", "safe and sound", "Geography", 46),
    _c("次", "cì", 4, "time (occurrence); order; next", "下次", "xià cì", "next time", "HSK Vocab", 46),
    _c("第", "dì", 4, "ordinal prefix (第一=first)", "第一次", "dì yī cì", "the first time", "HSK Vocab", 46),
    _c("段", "duàn", 4, "section; paragraph; period", "一段时间", "yī duàn shíjiān", "a period of time", "HSK Vocab", 46),
    _c("篇", "piān", 1, "measure for articles/essays", "一篇文章", "yī piān wénzhāng", "an article", "HSK Vocab", 46),

    # -- Week 47: Animals --
    _c("猫", "māo", 1, "cat", "小猫", "xiǎo māo", "kitten", "Animals", 47),
    _c("狗", "gǒu", 3, "dog", "小狗", "xiǎo gǒu", "puppy", "Animals", 47),
    _c("鱼", "yú", 2, "fish", "吃鱼", "chī yú", "eat fish", "Animals", 47),
    _c("马", "mǎ", 3, "horse; (马上=immediately)", "马上", "mǎshàng", "immediately; right away", "Animals", 47),
    _c("虫", "chóng", 2, "insect; bug; worm", "虫子", "chóngzi", "bug; insect", "Animals", 47),
    _c("象", "xiàng", 4, "elephant; image; shape", "大象", "dà xiàng", "elephant", "Animals", 47),
    _c("借", "jiè", 4, "to borrow; to lend", "借书", "jiè shū", "borrow a book", "Verbs", 47),
    _c("相", "xiāng", 1, "mutually; each other; to look at", "相信", "xiāngxìn", "to believe", "Verbs", 47),
    _c("护", "hù", 4, "to protect; to guard", "护照", "hùzhào", "passport", "Verbs", 47),
    _c("检", "jiǎn", 3, "to check; to examine; to inspect", "检查", "jiǎnchá", "to check; inspect", "Verbs", 47),
    _c("查", "chá", 2, "to check; to look up; to inspect", "检查身体", "jiǎnchá shēntǐ", "health checkup", "Verbs", 47),

    # -- Week 48: Verbs --
    _c("死", "sǐ", 3, "to die; death; extremely (slang)", "累死了", "lèi sǐ le", "dead tired", "Verbs", 48),
    _c("活", "huó", 2, "to live; alive; lively; work", "生活", "shēnghuó", "life; to live", "Verbs", 48),
    _c("掉", "diào", 4, "to fall; to drop; to lose", "掉了", "diào le", "dropped / fell", "Verbs", 48),
    _c("算", "suàn", 4, "to count; to calculate; to plan", "打算", "dǎsuàn", "to plan; intention", "Verbs", 48),
    _c("刷", "shuā", 1, "to brush; to swipe", "刷牙", "shuā yá", "brush teeth", "Verbs", 48),
    _c("练", "liàn", 4, "to practice; to train; exercise", "练习", "liànxí", "to practice; exercise", "Verbs", 48),
    _c("懒", "lǎn", 3, "lazy", "太懒了", "tài lǎn le", "too lazy", "Verbs", 48),
    _c("够", "gòu", 4, "enough; sufficient; quite", "够了", "gòu le", "That's enough!", "Verbs", 48),
    _c("容", "róng", 2, "to contain; to tolerate; face", "容易", "róngyì", "easy", "Verbs", 48),
    _c("差", "chà", 4, "to differ; poor; lacking; almost", "差不多", "chà bu duō", "almost; about the same", "Verbs", 48),
    _c("表", "biǎo", 3, "surface; to express; watch; form", "表示", "biǎoshì", "to express; to show", "Verbs", 48),
    _c("示", "shì", 4, "to show; to indicate; to reveal", "表示", "biǎoshì", "to express", "Verbs", 48),

    # -- Week 49: HSK Vocab --
    _c("星", "xīng", 1, "star; satellite; (星期=week)", "星期天", "xīngqītiān", "Sunday", "HSK Vocab", 49),
    _c("漂", "piào", 4, "pretty (漂亮); to float (piāo)", "漂亮", "piàoliang", "pretty; beautiful", "HSK Vocab", 49),
    _c("便", "pián", 2, "cheap (便宜); convenient (biàn)", "便宜", "piányi", "cheap; inexpensive", "HSK Vocab", 49),
    _c("宜", "yí", 2, "suitable; appropriate (便宜=cheap)", "便宜", "piányi", "cheap", "HSK Vocab", 49),
    _c("舒", "shū", 1, "comfortable; to stretch (舒服)", "舒服", "shūfu", "comfortable", "HSK Vocab", 49),
    _c("应", "yīng", 1, "should; ought to; to respond", "应该", "yīnggāi", "should; ought to", "HSK Vocab", 49),
    _c("该", "gāi", 1, "should; ought to; that", "应该", "yīnggāi", "should", "HSK Vocab", 49),
    _c("往", "wǎng", 3, "toward; to go; past; previous", "往前走", "wǎng qián zǒu", "go forward", "HSK Vocab", 49),
    _c("跟", "gēn", 1, "with; to follow; and", "跟我来", "gēn wǒ lái", "Follow me", "HSK Vocab", 49),
    _c("猪", "zhū", 1, "pig; pork", "猪肉", "zhūròu", "pork", "HSK Vocab", 49),
    _c("鲜", "xiān", 1, "fresh; delicious; bright", "新鲜", "xīnxiān", "fresh", "HSK Vocab", 49),
    _c("香", "xiāng", 1, "fragrant; delicious; popular", "香蕉", "xiāngjiāo", "banana", "HSK Vocab", 49),

    # -- Week 50: HSK Vocab --
    _c("甜", "tián", 2, "sweet", "甜的", "tián de", "sweet (flavor)", "HSK Vocab", 50),
    _c("咸", "xián", 2, "salty", "太咸了", "tài xián le", "too salty", "HSK Vocab", 50),
    _c("辣", "là", 4, "spicy; hot (taste)", "太辣了", "tài là le", "too spicy!", "HSK Vocab", 50),
    _c("健", "jiàn", 4, "healthy; strong (健康)", "健康", "jiànkāng", "healthy; health", "HSK Vocab", 50),
    _c("康", "kāng", 1, "healthy; well-being (健康)", "身体健康", "shēntǐ jiànkāng", "good health", "HSK Vocab", 50),
    _c("闲", "xián", 2, "idle; free time; leisure", "有空闲", "yǒu kòngxián", "have free time", "HSK Vocab", 50),
    _c("牙", "yá", 2, "tooth", "刷牙", "shuā yá", "brush teeth", "HSK Vocab", 50),
    _c("脸", "liǎn", 3, "face", "洗脸", "xǐ liǎn", "wash face", "HSK Vocab", 50),
    _c("声", "shēng", 1, "sound; voice; tone", "声音", "shēngyīn", "sound; voice", "HSK Vocab", 50),
    _c("目", "mù", 4, "eye; item; list (节目=program)", "节目", "jiémù", "program; show", "HSK Vocab", 50),
    _c("休", "xiū", 1, "to rest; to cease (休息)", "休息", "xiūxi", "to rest", "HSK Vocab", 50),
    _c("息", "xī", 1, "to rest; breath; news; interest", "休息一下", "xiūxi yīxià", "rest a bit", "HSK Vocab", 50),

    # -- Week 51: HSK Vocab --
    _c("越", "yuè", 4, "to cross; more and more (越来越)", "越来越好", "yuè lái yuè hǎo", "getting better and better", "HSK Vocab", 51),
    _c("极", "jí", 2, "extremely; pole; utmost", "好极了", "hǎo jí le", "Wonderful!", "HSK Vocab", 51),
    _c("刚", "gāng", 1, "just now; just; barely", "刚才", "gāngcái", "just now; a moment ago", "HSK Vocab", 51),
    _c("附", "fù", 4, "nearby; to attach (附近=nearby)", "附近", "fùjìn", "nearby; vicinity", "HSK Vocab", 51),
    _c("喂", "wèi", 4, "hello (on phone); hey; to feed", "喂，你好", "wèi, nǐ hǎo", "Hello? (answering phone)", "HSK Vocab", 51),
    _c("数", "shù", 4, "number; to count (shǔ)", "数学", "shùxué", "mathematics", "HSK Vocab", 51),
    _c("冰", "bīng", 1, "ice; cold; to freeze", "冰水", "bīng shuǐ", "ice water", "HSK Vocab", 51),
    _c("聪", "cōng", 1, "clever; smart (聪明)", "聪明", "cōngming", "smart; clever", "HSK Vocab", 51),
    _c("奇", "qí", 2, "strange; odd; wonderful", "奇怪", "qíguài", "strange; weird", "HSK Vocab", 51),
    _c("怪", "guài", 4, "strange; to blame; monster", "真奇怪", "zhēn qíguài", "How strange!", "HSK Vocab", 51),
    _c("突", "tū", 1, "suddenly; to protrude (突然)", "突然", "tūrán", "suddenly", "HSK Vocab", 51),
    _c("危", "wēi", 1, "danger; to endanger (危险)", "危险", "wēixiǎn", "dangerous", "HSK Vocab", 51),

    # -- Week 52: HSK Vocab --
    _c("险", "xiǎn", 3, "danger; risk; insurance", "危险", "wēixiǎn", "dangerous", "HSK Vocab", 52),
    _c("努", "nǔ", 3, "to strive; effort (努力)", "努力学习", "nǔlì xuéxí", "study hard", "HSK Vocab", 52),
    _c("必", "bì", 4, "must; certainly; necessary", "必须", "bìxū", "must; have to", "HSK Vocab", 52),
    _c("须", "xū", 1, "must; beard; to need (必须)", "必须去", "bìxū qù", "must go", "HSK Vocab", 52),
    _c("季", "jì", 4, "season; quarter (of year)", "四季", "sì jì", "four seasons", "HSK Vocab", 52),
    _c("忽", "hū", 1, "suddenly; to neglect (忽然)", "忽然", "hūrán", "suddenly", "HSK Vocab", 52),
    _c("味", "wèi", 4, "taste; flavor; smell", "味道", "wèidào", "flavor; taste", "HSK Vocab", 52),
    _c("饱", "bǎo", 3, "full (after eating); satisfied", "吃饱了", "chī bǎo le", "ate until full", "HSK Vocab", 52),
    _c("份", "fèn", 4, "portion; share; copy", "一份", "yī fèn", "a portion/copy", "HSK Vocab", 52),
    _c("戴", "dài", 4, "to wear (hat/glasses/watch)", "戴帽子", "dài màozi", "wear a hat", "HSK Vocab", 52),
    _c("讲", "jiǎng", 3, "to speak; to tell; to explain", "讲故事", "jiǎng gùshi", "tell a story", "HSK Vocab", 52),

    # -- Week 53: HSK Vocab --
    _c("故", "gù", 4, "old; reason; 故事=story", "故事", "gùshi", "story", "HSK Vocab", 53),
    _c("响", "xiǎng", 3, "to ring; to sound; loud; influence", "影响", "yǐngxiǎng", "influence; to affect", "HSK Vocab", 53),
    _c("解", "jiě", 3, "to understand; to solve; to untie", "了解", "liǎojiě", "to understand", "HSK Vocab", 53),
    _c("按", "àn", 4, "to press; to push; according to", "按时", "ànshí", "on time; on schedule", "HSK Vocab", 53),
    _c("普", "pǔ", 3, "universal; general (普通)", "普通话", "pǔtōnghuà", "Mandarin Chinese", "HSK Vocab", 53),
    _c("通", "tōng", 1, "through; to communicate; common", "交通", "jiāotōng", "traffic; transport", "HSK Vocab", 53),
    _c("遇", "yù", 4, "to meet; to encounter", "遇到", "yùdào", "to encounter; to meet", "HSK Vocab", 53),
    _c("复", "fù", 4, "to repeat; to review; again; complex", "复习", "fùxí", "to review (study)", "HSK Vocab", 53),

    # -- Week 54: HSK Vocab --
    _c("留", "liú", 2, "to stay; to keep; to leave behind", "留学", "liúxué", "study abroad", "HSK Vocab", 54),
    _c("程", "chéng", 2, "journey; process; procedure", "过程", "guòchéng", "process; course", "HSK Vocab", 54),
    _c("愿", "yuàn", 4, "to wish; to want; willing", "愿意", "yuànyì", "willing; to want to", "HSK Vocab", 54),
    _c("秒", "miǎo", 3, "second (unit of time)", "几秒钟", "jǐ miǎo zhōng", "a few seconds", "HSK Vocab", 54),
    _c("温", "wēn", 1, "warm; temperature; to review", "温度", "wēndù", "temperature", "HSK Vocab", 54),
    _c("饮", "yǐn", 3, "to drink; beverage (饮料)", "饮料", "yǐnliào", "beverage; drink", "HSK Vocab", 54),
    _c("料", "liào", 4, "material; to expect; feed", "饮料", "yǐnliào", "beverage", "HSK Vocab", 54),
    _c("汽", "qì", 4, "steam; gas; vapor (汽车=car)", "汽车", "qìchē", "car; automobile", "HSK Vocab", 54),
]

# Total: 600 characters
assert len(CHARACTERS) == 600, f"Expected 600 characters, got {len(CHARACTERS)}"
